#!/bin/bash

make
#g++ -Wall -Werror -Wextra -O2 `root-config --cflags --libs` -lTMVA -lRooFitCore -lRooFit -MMD -MF ./build/Performance/photons/photonRecoAna.d Performance/photons/photonRecoAna.C -o Performance/photons/photonRecoAna.exe
#echo "g++ -Wall -Werror -Wextra -O2 `root-config --cflags --libs` -lTMVA -lRooFitCore -lRooFit -MMD -MF ./build/Performance/photons/photonRecoAna.d Performance/photons/photonRecoAna.C -o Performance/photons/photonRecoAna.exe"

~/code/scripts/myRun.sh Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_AllQCDPhoton30_Hydjet_Cymbal_MB.log &
echo "myRun Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_AllQCDPhoton30_Hydjet_Cymbal_MB.log &"

~/code/scripts/myRun.sh Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.GED.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.log &
echo "myRun Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.GED.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.log &"

## SIG
~/code/scripts/myRun.sh Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.SIG.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_AllQCDPhoton30_Hydjet_Cymbal_MB.log &
echo "myRun Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.SIG.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_AllQCDPhoton30_Hydjet_Cymbal_MB.log &"

~/code/scripts/myRun.sh Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.SIG.GED.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.log &
echo "myRun Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.exe Configurations/Performance/photons/photonRecoAna.fake.AllQCD.SIG.GED.conf /mnt/hadoop/cms/store/user/tatar/official/Pythia8_AllQCDPhoton30_Hydjet_Cymbal_MB/HINPbPbWinter16DR-75X_mcRun2_HeavyIon_v14-v1-FOREST/0.root /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.root &> /export/d00/scratch/tatar/EWJTA-out/Performance/photons/photonRecoAna_fake_SIG_GED_AllQCDPhoton30_Hydjet_Cymbal_MB.log &"

