/*
 * class to manage dielectron tree, tree of electron pairs
 */

#ifndef TREEHEADERS_DIELECTRONTREE_H_
#define TREEHEADERS_DIELECTRONTREE_H_

#include <TTree.h>
#include <TLorentzVector.h>

#include <vector>

#include "ggHiNtuplizerTree.h"

class dielectron {
public :
  dielectron(){
      mass = 0.000511;

      eleCharge_1 = 0;
      eleChargeConsistent_1 = 0;
      eleEn_1 = 0;
      eleD0_1 = 0;
      eleDz_1 = 0;
      eleD0Err_1 = 0;
      eleDzErr_1 = 0;
      eleTrkPt_1 = 0;
      eleTrkEta_1 = 0;
      eleTrkPhi_1 = 0;
      eleTrkCharge_1 = 0;
      eleTrkChi2_1 = 0;
      eleTrkNdof_1 = 0;
      eleTrkNormalizedChi2_1 = 0;
      elePt_1 = 0;
      eleEta_1 = 0;
      elePhi_1 = 0;
      eleSCEn_1 = 0;
      eleESEn_1 = 0;
      eleSCEta_1 = 0;
      eleSCPhi_1 = 0;
      eleSCRawEn_1 = 0;
      eleSCEtaWidth_1 = 0;
      eleSCPhiWidth_1 = 0;
      eleHoverE_1 = 0;
      eleEoverP_1 = 0;
      eleEoverPInv_1 = 0;
      eleBrem_1 = 0;
      eledEtaAtVtx_1 = 0;
      eledPhiAtVtx_1 = 0;
      eleSigmaIEtaIEta_1 = 0;
      eleSigmaIEtaIEta_2012_1 = 0;
      eleSigmaIPhiIPhi_1 = 0;
      eleMissHits_1 = 0;
      eleESEffSigmaRR_1 = 0;
      elePFChIso_1 = 0;
      elePFPhoIso_1 = 0;
      elePFNeuIso_1 = 0;
      elePFPUIso_1 = 0;
      eleBC1E_1 = 0;
      eleBC1Eta_1 = 0;
      eleBC2E_1 = 0;
      eleBC2Eta_1 = 0;

      eleCharge_2 = 0;
      eleChargeConsistent_2 = 0;
      eleEn_2 = 0;
      eleD0_2 = 0;
      eleDz_2 = 0;
      eleD0Err_2 = 0;
      eleDzErr_2 = 0;
      eleTrkPt_2 = 0;
      eleTrkEta_2 = 0;
      eleTrkPhi_2 = 0;
      eleTrkCharge_2 = 0;
      eleTrkChi2_2 = 0;
      eleTrkNdof_2 = 0;
      eleTrkNormalizedChi2_2 = 0;
      elePt_2 = 0;
      eleEta_2 = 0;
      elePhi_2 = 0;
      eleSCEn_2 = 0;
      eleESEn_2 = 0;
      eleSCEta_2 = 0;
      eleSCPhi_2 = 0;
      eleSCRawEn_2 = 0;
      eleSCEtaWidth_2 = 0;
      eleSCPhiWidth_2 = 0;
      eleHoverE_2 = 0;
      eleEoverP_2 = 0;
      eleEoverPInv_2 = 0;
      eleBrem_2 = 0;
      eledEtaAtVtx_2 = 0;
      eledPhiAtVtx_2 = 0;
      eleSigmaIEtaIEta_2 = 0;
      eleSigmaIEtaIEta_2012_2 = 0;
      eleSigmaIPhiIPhi_2 = 0;
      eleMissHits_2 = 0;
      eleESEffSigmaRR_2 = 0;
      elePFChIso_2 = 0;
      elePFPhoIso_2 = 0;
      elePFNeuIso_2 = 0;
      elePFPUIso_2 = 0;
      eleBC1E_2 = 0;
      eleBC1Eta_2 = 0;
      eleBC2E_2 = 0;
      eleBC2Eta_2 = 0;

      diEleM = 0;
      diEleEn = 0;
      diElePt = 0;
      diEleEta = 0;
      diElePhi = 0;
  };
  ~dielectron(){};
  void setupDiElectronTree(TTree *t);
  void branchDiElectronTree(TTree *t);
  void makeDiElectronPairs(ggHiNtuplizer &tggHiNtuplizer, bool doSizeCheck = true);

  double mass;
  // Declaration of leaf types
  Int_t           nEle;
  std::vector<int>     *eleCharge_1;
  std::vector<int>     *eleChargeConsistent_1;
  std::vector<float>   *eleEn_1;
  std::vector<float>   *eleD0_1;
  std::vector<float>   *eleDz_1;
  std::vector<float>   *eleD0Err_1;
  std::vector<float>   *eleDzErr_1;
  std::vector<float>   *eleTrkPt_1;
  std::vector<float>   *eleTrkEta_1;
  std::vector<float>   *eleTrkPhi_1;
  std::vector<int>     *eleTrkCharge_1;
  std::vector<float>   *eleTrkChi2_1;
  std::vector<float>   *eleTrkNdof_1;
  std::vector<float>   *eleTrkNormalizedChi2_1;
  std::vector<float>   *elePt_1;
  std::vector<float>   *eleEta_1;
  std::vector<float>   *elePhi_1;
  std::vector<float>   *eleSCEn_1;
  std::vector<float>   *eleESEn_1;
  std::vector<float>   *eleSCEta_1;
  std::vector<float>   *eleSCPhi_1;
  std::vector<float>   *eleSCRawEn_1;
  std::vector<float>   *eleSCEtaWidth_1;
  std::vector<float>   *eleSCPhiWidth_1;
  std::vector<float>   *eleHoverE_1;
  std::vector<float>   *eleEoverP_1;
  std::vector<float>   *eleEoverPInv_1;
  std::vector<float>   *eleBrem_1;
  std::vector<float>   *eledEtaAtVtx_1;
  std::vector<float>   *eledPhiAtVtx_1;
  std::vector<float>   *eleSigmaIEtaIEta_1;
  std::vector<float>   *eleSigmaIEtaIEta_2012_1;
  std::vector<float>   *eleSigmaIPhiIPhi_1;
  std::vector<int>     *eleMissHits_1;
  std::vector<float>   *eleESEffSigmaRR_1;
  std::vector<float>   *elePFChIso_1;
  std::vector<float>   *elePFPhoIso_1;
  std::vector<float>   *elePFNeuIso_1;
  std::vector<float>   *elePFPUIso_1;
  std::vector<float>   *eleBC1E_1;
  std::vector<float>   *eleBC1Eta_1;
  std::vector<float>   *eleBC2E_1;
  std::vector<float>   *eleBC2Eta_1;

  std::vector<int>     *eleCharge_2;
  std::vector<int>     *eleChargeConsistent_2;
  std::vector<float>   *eleEn_2;
  std::vector<float>   *eleD0_2;
  std::vector<float>   *eleDz_2;
  std::vector<float>   *eleD0Err_2;
  std::vector<float>   *eleDzErr_2;
  std::vector<float>   *eleTrkPt_2;
  std::vector<float>   *eleTrkEta_2;
  std::vector<float>   *eleTrkPhi_2;
  std::vector<int>     *eleTrkCharge_2;
  std::vector<float>   *eleTrkChi2_2;
  std::vector<float>   *eleTrkNdof_2;
  std::vector<float>   *eleTrkNormalizedChi2_2;
  std::vector<float>   *elePt_2;
  std::vector<float>   *eleEta_2;
  std::vector<float>   *elePhi_2;
  std::vector<float>   *eleSCEn_2;
  std::vector<float>   *eleESEn_2;
  std::vector<float>   *eleSCEta_2;
  std::vector<float>   *eleSCPhi_2;
  std::vector<float>   *eleSCRawEn_2;
  std::vector<float>   *eleSCEtaWidth_2;
  std::vector<float>   *eleSCPhiWidth_2;
  std::vector<float>   *eleHoverE_2;
  std::vector<float>   *eleEoverP_2;
  std::vector<float>   *eleEoverPInv_2;
  std::vector<float>   *eleBrem_2;
  std::vector<float>   *eledEtaAtVtx_2;
  std::vector<float>   *eledPhiAtVtx_2;
  std::vector<float>   *eleSigmaIEtaIEta_2;
  std::vector<float>   *eleSigmaIEtaIEta_2012_2;
  std::vector<float>   *eleSigmaIPhiIPhi_2;
  std::vector<int>     *eleMissHits_2;
  std::vector<float>   *eleESEffSigmaRR_2;
  std::vector<float>   *elePFChIso_2;
  std::vector<float>   *elePFPhoIso_2;
  std::vector<float>   *elePFNeuIso_2;
  std::vector<float>   *elePFPUIso_2;
  std::vector<float>   *eleBC1E_2;
  std::vector<float>   *eleBC1Eta_2;
  std::vector<float>   *eleBC2E_2;
  std::vector<float>   *eleBC2Eta_2;

  std::vector<float>   *diEleM;
  std::vector<float>   *diEleEn;
  std::vector<float>   *diElePt;
  std::vector<float>   *diEleEta;
  std::vector<float>   *diElePhi;

  // List of branches
  TBranch        *b_nEle;
  TBranch        *b_eleCharge_1;
  TBranch        *b_eleChargeConsistent_1;
  TBranch        *b_eleEn_1;
  TBranch        *b_eleD0_1;
  TBranch        *b_eleDz_1;
  TBranch        *b_eleD0Err_1;
  TBranch        *b_eleDzErr_1;
  TBranch        *b_eleTrkPt_1;
  TBranch        *b_eleTrkEta_1;
  TBranch        *b_eleTrkPhi_1;
  TBranch        *b_eleTrkCharge_1;
  TBranch        *b_eleTrkChi2_1;
  TBranch        *b_eleTrkNdof_1;
  TBranch        *b_eleTrkNormalizedChi2_1;
  TBranch        *b_elePt_1;
  TBranch        *b_eleEta_1;
  TBranch        *b_elePhi_1;
  TBranch        *b_eleSCEn_1;
  TBranch        *b_eleESEn_1;
  TBranch        *b_eleSCEta_1;
  TBranch        *b_eleSCPhi_1;
  TBranch        *b_eleSCRawEn_1;
  TBranch        *b_eleSCEtaWidth_1;
  TBranch        *b_eleSCPhiWidth_1;
  TBranch        *b_eleHoverE_1;
  TBranch        *b_eleEoverP_1;
  TBranch        *b_eleEoverPInv_1;
  TBranch        *b_eleBrem_1;
  TBranch        *b_eledEtaAtVtx_1;
  TBranch        *b_eledPhiAtVtx_1;
  TBranch        *b_eleSigmaIEtaIEta_1;
  TBranch        *b_eleSigmaIEtaIEta_2012_1;
  TBranch        *b_eleSigmaIPhiIPhi_1;
  TBranch        *b_eleMissHits_1;
  TBranch        *b_eleESEffSigmaRR_1;
  TBranch        *b_elePFChIso_1;
  TBranch        *b_elePFPhoIso_1;
  TBranch        *b_elePFNeuIso_1;
  TBranch        *b_elePFPUIso_1;
  TBranch        *b_eleBC1E_1;
  TBranch        *b_eleBC1Eta_1;
  TBranch        *b_eleBC2E_1;
  TBranch        *b_eleBC2Eta_1;

  TBranch        *b_eleCharge_2;
  TBranch        *b_eleChargeConsistent_2;
  TBranch        *b_eleEn_2;
  TBranch        *b_eleD0_2;
  TBranch        *b_eleDz_2;
  TBranch        *b_eleD0Err_2;
  TBranch        *b_eleDzErr_2;
  TBranch        *b_eleTrkPt_2;
  TBranch        *b_eleTrkEta_2;
  TBranch        *b_eleTrkPhi_2;
  TBranch        *b_eleTrkCharge_2;
  TBranch        *b_eleTrkChi2_2;
  TBranch        *b_eleTrkNdof_2;
  TBranch        *b_eleTrkNormalizedChi2_2;
  TBranch        *b_elePt_2;
  TBranch        *b_eleEta_2;
  TBranch        *b_elePhi_2;
  TBranch        *b_eleSCEn_2;
  TBranch        *b_eleESEn_2;
  TBranch        *b_eleSCEta_2;
  TBranch        *b_eleSCPhi_2;
  TBranch        *b_eleSCRawEn_2;
  TBranch        *b_eleSCEtaWidth_2;
  TBranch        *b_eleSCPhiWidth_2;
  TBranch        *b_eleHoverE_2;
  TBranch        *b_eleEoverP_2;
  TBranch        *b_eleEoverPInv_2;
  TBranch        *b_eleBrem_2;
  TBranch        *b_eledEtaAtVtx_2;
  TBranch        *b_eledPhiAtVtx_2;
  TBranch        *b_eleSigmaIEtaIEta_2;
  TBranch        *b_eleSigmaIEtaIEta_2012_2;
  TBranch        *b_eleSigmaIPhiIPhi_2;
  TBranch        *b_eleMissHits_2;
  TBranch        *b_eleESEffSigmaRR_2;
  TBranch        *b_elePFChIso_2;
  TBranch        *b_elePFPhoIso_2;
  TBranch        *b_elePFNeuIso_2;
  TBranch        *b_elePFPUIso_2;
  TBranch        *b_eleBC1E_2;
  TBranch        *b_eleBC1Eta_2;
  TBranch        *b_eleBC2E_2;
  TBranch        *b_eleBC2Eta_2;

  TBranch        *b_diEleM;
  TBranch        *b_diEleEn;
  TBranch        *b_diElePt;
  TBranch        *b_diEleEta;
  TBranch        *b_diElePhi;

  // list of objects to be used when creating a diElectron Tree
  Int_t           nEle_out;
  std::vector<int>     eleCharge_1_out;
  std::vector<int>     eleChargeConsistent_1_out;
  std::vector<float>   eleEn_1_out;
  std::vector<float>   eleD0_1_out;
  std::vector<float>   eleDz_1_out;
  std::vector<float>   eleD0Err_1_out;
  std::vector<float>   eleDzErr_1_out;
  std::vector<float>   eleTrkPt_1_out;
  std::vector<float>   eleTrkEta_1_out;
  std::vector<float>   eleTrkPhi_1_out;
  std::vector<int>     eleTrkCharge_1_out;
  std::vector<float>   eleTrkChi2_1_out;
  std::vector<float>   eleTrkNdof_1_out;
  std::vector<float>   eleTrkNormalizedChi2_1_out;
  std::vector<float>   elePt_1_out;
  std::vector<float>   eleEta_1_out;
  std::vector<float>   elePhi_1_out;
  std::vector<float>   eleSCEn_1_out;
  std::vector<float>   eleESEn_1_out;
  std::vector<float>   eleSCEta_1_out;
  std::vector<float>   eleSCPhi_1_out;
  std::vector<float>   eleSCRawEn_1_out;
  std::vector<float>   eleSCEtaWidth_1_out;
  std::vector<float>   eleSCPhiWidth_1_out;
  std::vector<float>   eleHoverE_1_out;
  std::vector<float>   eleEoverP_1_out;
  std::vector<float>   eleEoverPInv_1_out;
  std::vector<float>   eleBrem_1_out;
  std::vector<float>   eledEtaAtVtx_1_out;
  std::vector<float>   eledPhiAtVtx_1_out;
  std::vector<float>   eleSigmaIEtaIEta_1_out;
  std::vector<float>   eleSigmaIEtaIEta_2012_1_out;
  std::vector<float>   eleSigmaIPhiIPhi_1_out;
  std::vector<int>     eleMissHits_1_out;
  std::vector<float>   eleESEffSigmaRR_1_out;
  std::vector<float>   elePFChIso_1_out;
  std::vector<float>   elePFPhoIso_1_out;
  std::vector<float>   elePFNeuIso_1_out;
  std::vector<float>   elePFPUIso_1_out;
  std::vector<float>   eleBC1E_1_out;
  std::vector<float>   eleBC1Eta_1_out;
  std::vector<float>   eleBC2E_1_out;
  std::vector<float>   eleBC2Eta_1_out;

  std::vector<int>     eleCharge_2_out;
  std::vector<int>     eleChargeConsistent_2_out;
  std::vector<float>   eleEn_2_out;
  std::vector<float>   eleD0_2_out;
  std::vector<float>   eleDz_2_out;
  std::vector<float>   eleD0Err_2_out;
  std::vector<float>   eleDzErr_2_out;
  std::vector<float>   eleTrkPt_2_out;
  std::vector<float>   eleTrkEta_2_out;
  std::vector<float>   eleTrkPhi_2_out;
  std::vector<int>     eleTrkCharge_2_out;
  std::vector<float>   eleTrkChi2_2_out;
  std::vector<float>   eleTrkNdof_2_out;
  std::vector<float>   eleTrkNormalizedChi2_2_out;
  std::vector<float>   elePt_2_out;
  std::vector<float>   eleEta_2_out;
  std::vector<float>   elePhi_2_out;
  std::vector<float>   eleSCEn_2_out;
  std::vector<float>   eleESEn_2_out;
  std::vector<float>   eleSCEta_2_out;
  std::vector<float>   eleSCPhi_2_out;
  std::vector<float>   eleSCRawEn_2_out;
  std::vector<float>   eleSCEtaWidth_2_out;
  std::vector<float>   eleSCPhiWidth_2_out;
  std::vector<float>   eleHoverE_2_out;
  std::vector<float>   eleEoverP_2_out;
  std::vector<float>   eleEoverPInv_2_out;
  std::vector<float>   eleBrem_2_out;
  std::vector<float>   eledEtaAtVtx_2_out;
  std::vector<float>   eledPhiAtVtx_2_out;
  std::vector<float>   eleSigmaIEtaIEta_2_out;
  std::vector<float>   eleSigmaIEtaIEta_2012_2_out;
  std::vector<float>   eleSigmaIPhiIPhi_2_out;
  std::vector<int>     eleMissHits_2_out;
  std::vector<float>   eleESEffSigmaRR_2_out;
  std::vector<float>   elePFChIso_2_out;
  std::vector<float>   elePFPhoIso_2_out;
  std::vector<float>   elePFNeuIso_2_out;
  std::vector<float>   elePFPUIso_2_out;
  std::vector<float>   eleBC1E_2_out;
  std::vector<float>   eleBC1Eta_2_out;
  std::vector<float>   eleBC2E_2_out;
  std::vector<float>   eleBC2Eta_2_out;

  std::vector<float>   diEleM_out;
  std::vector<float>   diEleEn_out;
  std::vector<float>   diElePt_out;
  std::vector<float>   diEleEta_out;
  std::vector<float>   diElePhi_out;
};

void dielectron::setupDiElectronTree(TTree *t)
{
    // Set branch addresses and branch pointers
    if (t->GetBranch("nEle"))  t->SetBranchAddress("nEle", &nEle, &b_nEle);

    if (t->GetBranch("eleCharge_1"))  t->SetBranchAddress("eleCharge_1", &eleCharge_1, &b_eleCharge_1);
    if (t->GetBranch("eleChargeConsistent_1"))  t->SetBranchAddress("eleChargeConsistent_1", &eleChargeConsistent_1, &b_eleChargeConsistent_1);
    if (t->GetBranch("eleEn_1"))  t->SetBranchAddress("eleEn_1", &eleEn_1, &b_eleEn_1);
    if (t->GetBranch("eleD0_1"))  t->SetBranchAddress("eleD0_1", &eleD0_1, &b_eleD0_1);
    if (t->GetBranch("eleDz_1"))  t->SetBranchAddress("eleDz_1", &eleDz_1, &b_eleDz_1);
    if (t->GetBranch("eleD0Err_1"))  t->SetBranchAddress("eleD0Err_1", &eleD0Err_1, &b_eleD0Err_1);
    if (t->GetBranch("eleDzErr_1"))  t->SetBranchAddress("eleDzErr_1", &eleDzErr_1, &b_eleDzErr_1);
    if (t->GetBranch("eleTrkPt_1"))  t->SetBranchAddress("eleTrkPt_1", &eleTrkPt_1, &b_eleTrkPt_1);
    if (t->GetBranch("eleTrkEta_1"))  t->SetBranchAddress("eleTrkEta_1", &eleTrkEta_1, &b_eleTrkEta_1);
    if (t->GetBranch("eleTrkPhi_1"))  t->SetBranchAddress("eleTrkPhi_1", &eleTrkPhi_1, &b_eleTrkPhi_1);
    if (t->GetBranch("eleTrkCharge_1"))  t->SetBranchAddress("eleTrkCharge_1", &eleTrkCharge_1, &b_eleTrkCharge_1);
    if (t->GetBranch("eleTrkChi2_1"))  t->SetBranchAddress("eleTrkChi2_1", &eleTrkChi2_1, &b_eleTrkChi2_1);
    if (t->GetBranch("eleTrkNdof_1"))  t->SetBranchAddress("eleTrkNdof_1", &eleTrkNdof_1, &b_eleTrkNdof_1);
    if (t->GetBranch("eleTrkNormalizedChi2_1"))  t->SetBranchAddress("eleTrkNormalizedChi2_1", &eleTrkNormalizedChi2_1, &b_eleTrkNormalizedChi2_1);
    if (t->GetBranch("elePt_1"))  t->SetBranchAddress("elePt_1", &elePt_1, &b_elePt_1);
    if (t->GetBranch("eleEta_1"))  t->SetBranchAddress("eleEta_1", &eleEta_1, &b_eleEta_1);
    if (t->GetBranch("elePhi_1"))  t->SetBranchAddress("elePhi_1", &elePhi_1, &b_elePhi_1);
    if (t->GetBranch("eleSCEn_1"))  t->SetBranchAddress("eleSCEn_1", &eleSCEn_1, &b_eleSCEn_1);
    if (t->GetBranch("eleESEn_1"))  t->SetBranchAddress("eleESEn_1", &eleESEn_1, &b_eleESEn_1);
    if (t->GetBranch("eleSCEta_1"))  t->SetBranchAddress("eleSCEta_1", &eleSCEta_1, &b_eleSCEta_1);
    if (t->GetBranch("eleSCPhi_1"))  t->SetBranchAddress("eleSCPhi_1", &eleSCPhi_1, &b_eleSCPhi_1);
    if (t->GetBranch("eleSCRawEn_1"))  t->SetBranchAddress("eleSCRawEn_1", &eleSCRawEn_1, &b_eleSCRawEn_1);
    if (t->GetBranch("eleSCEtaWidth_1"))  t->SetBranchAddress("eleSCEtaWidth_1", &eleSCEtaWidth_1, &b_eleSCEtaWidth_1);
    if (t->GetBranch("eleSCPhiWidth_1"))  t->SetBranchAddress("eleSCPhiWidth_1", &eleSCPhiWidth_1, &b_eleSCPhiWidth_1);
    if (t->GetBranch("eleHoverE_1"))  t->SetBranchAddress("eleHoverE_1", &eleHoverE_1, &b_eleHoverE_1);
    if (t->GetBranch("eleEoverP_1"))  t->SetBranchAddress("eleEoverP_1", &eleEoverP_1, &b_eleEoverP_1);
    if (t->GetBranch("eleEoverPInv_1"))  t->SetBranchAddress("eleEoverPInv_1", &eleEoverPInv_1, &b_eleEoverPInv_1);
    if (t->GetBranch("eleBrem_1"))  t->SetBranchAddress("eleBrem_1", &eleBrem_1, &b_eleBrem_1);
    if (t->GetBranch("eledEtaAtVtx_1"))  t->SetBranchAddress("eledEtaAtVtx_1", &eledEtaAtVtx_1, &b_eledEtaAtVtx_1);
    if (t->GetBranch("eledPhiAtVtx_1"))  t->SetBranchAddress("eledPhiAtVtx_1", &eledPhiAtVtx_1, &b_eledPhiAtVtx_1);
    if (t->GetBranch("eleSigmaIEtaIEta_1"))  t->SetBranchAddress("eleSigmaIEtaIEta_1", &eleSigmaIEtaIEta_1, &b_eleSigmaIEtaIEta_1);
    if (t->GetBranch("eleSigmaIEtaIEta_1"))  t->SetBranchAddress("eleSigmaIEtaIEta_2012_1", &eleSigmaIEtaIEta_2012_1, &b_eleSigmaIEtaIEta_2012_1);
    if (t->GetBranch("eleSigmaIPhiIPhi_1"))  t->SetBranchAddress("eleSigmaIPhiIPhi_1", &eleSigmaIPhiIPhi_1, &b_eleSigmaIPhiIPhi_1);
    if (t->GetBranch("eleMissHits_1"))  t->SetBranchAddress("eleMissHits_1", &eleMissHits_1, &b_eleMissHits_1);
    if (t->GetBranch("eleESEffSigmaRR_1"))  t->SetBranchAddress("eleESEffSigmaRR_1", &eleESEffSigmaRR_1, &b_eleESEffSigmaRR_1);
    if (t->GetBranch("elePFChIso_1"))  t->SetBranchAddress("elePFChIso_1", &elePFChIso_1, &b_elePFChIso_1);
    if (t->GetBranch("elePFPhoIso_1"))  t->SetBranchAddress("elePFPhoIso_1", &elePFPhoIso_1, &b_elePFPhoIso_1);
    if (t->GetBranch("elePFNeuIso_1"))  t->SetBranchAddress("elePFNeuIso_1", &elePFNeuIso_1, &b_elePFNeuIso_1);
    if (t->GetBranch("elePFPUIso_1"))  t->SetBranchAddress("elePFPUIso_1", &elePFPUIso_1, &b_elePFPUIso_1);
    if (t->GetBranch("eleBC1E_1"))  t->SetBranchAddress("eleBC1E_1", &eleBC1E_1, &b_eleBC1E_1);
    if (t->GetBranch("eleBC1Eta_1"))  t->SetBranchAddress("eleBC1Eta_1", &eleBC1Eta_1, &b_eleBC1Eta_1);
    if (t->GetBranch("eleBC2E_1"))  t->SetBranchAddress("eleBC2E_1", &eleBC2E_1, &b_eleBC2E_1);
    if (t->GetBranch("eleBC2Eta_1"))  t->SetBranchAddress("eleBC2Eta_1", &eleBC2Eta_1, &b_eleBC2Eta_1);

    if (t->GetBranch("eleCharge_2"))  t->SetBranchAddress("eleCharge_1", &eleCharge_1, &b_eleCharge_1);
    if (t->GetBranch("eleChargeConsistent_2"))  t->SetBranchAddress("eleChargeConsistent_1", &eleChargeConsistent_1, &b_eleChargeConsistent_1);
    if (t->GetBranch("eleEn_2"))  t->SetBranchAddress("eleEn_1", &eleEn_1, &b_eleEn_1);
    if (t->GetBranch("eleD0_2"))  t->SetBranchAddress("eleD0_1", &eleD0_1, &b_eleD0_1);
    if (t->GetBranch("eleDz_2"))  t->SetBranchAddress("eleDz_1", &eleDz_1, &b_eleDz_1);
    if (t->GetBranch("eleD0Err_2"))  t->SetBranchAddress("eleD0Err_1", &eleD0Err_1, &b_eleD0Err_1);
    if (t->GetBranch("eleDzErr_2"))  t->SetBranchAddress("eleDzErr_1", &eleDzErr_1, &b_eleDzErr_1);
    if (t->GetBranch("eleTrkPt_2"))  t->SetBranchAddress("eleTrkPt_1", &eleTrkPt_1, &b_eleTrkPt_1);
    if (t->GetBranch("eleTrkEta_2"))  t->SetBranchAddress("eleTrkEta_1", &eleTrkEta_1, &b_eleTrkEta_1);
    if (t->GetBranch("eleTrkPhi_2"))  t->SetBranchAddress("eleTrkPhi_1", &eleTrkPhi_1, &b_eleTrkPhi_1);
    if (t->GetBranch("eleTrkCharge_2"))  t->SetBranchAddress("eleTrkCharge_1", &eleTrkCharge_1, &b_eleTrkCharge_1);
    if (t->GetBranch("eleTrkChi2_2"))  t->SetBranchAddress("eleTrkChi2_1", &eleTrkChi2_1, &b_eleTrkChi2_1);
    if (t->GetBranch("eleTrkNdof_2"))  t->SetBranchAddress("eleTrkNdof_1", &eleTrkNdof_1, &b_eleTrkNdof_1);
    if (t->GetBranch("eleTrkNormalizedChi2_2"))  t->SetBranchAddress("eleTrkNormalizedChi2_1", &eleTrkNormalizedChi2_1, &b_eleTrkNormalizedChi2_1);
    if (t->GetBranch("elePt_2"))  t->SetBranchAddress("elePt_1", &elePt_1, &b_elePt_1);
    if (t->GetBranch("eleEta_2"))  t->SetBranchAddress("eleEta_1", &eleEta_1, &b_eleEta_1);
    if (t->GetBranch("elePhi_2"))  t->SetBranchAddress("elePhi_1", &elePhi_1, &b_elePhi_1);
    if (t->GetBranch("eleSCEn_2"))  t->SetBranchAddress("eleSCEn_1", &eleSCEn_1, &b_eleSCEn_1);
    if (t->GetBranch("eleESEn_2"))  t->SetBranchAddress("eleESEn_1", &eleESEn_1, &b_eleESEn_1);
    if (t->GetBranch("eleSCEta_2"))  t->SetBranchAddress("eleSCEta_1", &eleSCEta_1, &b_eleSCEta_1);
    if (t->GetBranch("eleSCPhi_2"))  t->SetBranchAddress("eleSCPhi_1", &eleSCPhi_1, &b_eleSCPhi_1);
    if (t->GetBranch("eleSCRawEn_2"))  t->SetBranchAddress("eleSCRawEn_1", &eleSCRawEn_1, &b_eleSCRawEn_1);
    if (t->GetBranch("eleSCEtaWidth_2"))  t->SetBranchAddress("eleSCEtaWidth_1", &eleSCEtaWidth_1, &b_eleSCEtaWidth_1);
    if (t->GetBranch("eleSCPhiWidth_2"))  t->SetBranchAddress("eleSCPhiWidth_1", &eleSCPhiWidth_1, &b_eleSCPhiWidth_1);
    if (t->GetBranch("eleHoverE_2"))  t->SetBranchAddress("eleHoverE_1", &eleHoverE_1, &b_eleHoverE_1);
    if (t->GetBranch("eleEoverP_2"))  t->SetBranchAddress("eleEoverP_1", &eleEoverP_1, &b_eleEoverP_1);
    if (t->GetBranch("eleEoverPInv_2"))  t->SetBranchAddress("eleEoverPInv_1", &eleEoverPInv_1, &b_eleEoverPInv_1);
    if (t->GetBranch("eleBrem_2"))  t->SetBranchAddress("eleBrem_1", &eleBrem_1, &b_eleBrem_1);
    if (t->GetBranch("eledEtaAtVtx_2"))  t->SetBranchAddress("eledEtaAtVtx_1", &eledEtaAtVtx_1, &b_eledEtaAtVtx_1);
    if (t->GetBranch("eledPhiAtVtx_2"))  t->SetBranchAddress("eledPhiAtVtx_1", &eledPhiAtVtx_1, &b_eledPhiAtVtx_1);
    if (t->GetBranch("eleSigmaIEtaIEta_2"))  t->SetBranchAddress("eleSigmaIEtaIEta_1", &eleSigmaIEtaIEta_1, &b_eleSigmaIEtaIEta_1);
    if (t->GetBranch("eleSigmaIEtaIEta_2"))  t->SetBranchAddress("eleSigmaIEtaIEta_2012_1", &eleSigmaIEtaIEta_2012_1, &b_eleSigmaIEtaIEta_2012_1);
    if (t->GetBranch("eleSigmaIPhiIPhi_2"))  t->SetBranchAddress("eleSigmaIPhiIPhi_1", &eleSigmaIPhiIPhi_1, &b_eleSigmaIPhiIPhi_1);
    if (t->GetBranch("eleMissHits_2"))  t->SetBranchAddress("eleMissHits_1", &eleMissHits_1, &b_eleMissHits_1);
    if (t->GetBranch("eleESEffSigmaRR_2"))  t->SetBranchAddress("eleESEffSigmaRR_1", &eleESEffSigmaRR_1, &b_eleESEffSigmaRR_1);
    if (t->GetBranch("elePFChIso_2"))  t->SetBranchAddress("elePFChIso_1", &elePFChIso_1, &b_elePFChIso_1);
    if (t->GetBranch("elePFPhoIso_2"))  t->SetBranchAddress("elePFPhoIso_1", &elePFPhoIso_1, &b_elePFPhoIso_1);
    if (t->GetBranch("elePFNeuIso_2"))  t->SetBranchAddress("elePFNeuIso_1", &elePFNeuIso_1, &b_elePFNeuIso_1);
    if (t->GetBranch("elePFPUIso_2"))  t->SetBranchAddress("elePFPUIso_1", &elePFPUIso_1, &b_elePFPUIso_1);
    if (t->GetBranch("eleBC1E_2"))  t->SetBranchAddress("eleBC1E_1", &eleBC1E_1, &b_eleBC1E_1);
    if (t->GetBranch("eleBC1Eta_2"))  t->SetBranchAddress("eleBC1Eta_1", &eleBC1Eta_1, &b_eleBC1Eta_1);
    if (t->GetBranch("eleBC2E_2"))  t->SetBranchAddress("eleBC2E_1", &eleBC2E_1, &b_eleBC2E_1);
    if (t->GetBranch("eleBC2Eta_2"))  t->SetBranchAddress("eleBC2Eta_1", &eleBC2Eta_1, &b_eleBC2Eta_1);

    if (t->GetBranch("diEleM"))  t->SetBranchAddress("diEleM", &diEleM, &b_diEleM);
    if (t->GetBranch("diEleEn"))  t->SetBranchAddress("diEleEn", &diEleEn, &b_diEleEn);
    if (t->GetBranch("diElePt"))  t->SetBranchAddress("diElePt", &diElePt, &b_diElePt);
    if (t->GetBranch("diEleEta"))  t->SetBranchAddress("diEleEta", &diEleEta, &b_diEleEta);
    if (t->GetBranch("diElePhi"))  t->SetBranchAddress("diElePhi", &diElePhi, &b_diElePhi);
}

void dielectron::branchDiElectronTree(TTree *t)
{
    t->Branch("nEle", &nEle_out);

    t->Branch("eleCharge_1", &eleCharge_1_out);
    t->Branch("eleChargeConsistent_1", &eleChargeConsistent_1_out);
    t->Branch("eleEn_1", &eleEn_1_out);
    t->Branch("eleD0_1", &eleD0_1_out);
    t->Branch("eleDz_1", &eleDz_1_out);
    t->Branch("eleD0Err_1", &eleD0Err_1_out);
    t->Branch("eleDzErr_1", &eleDzErr_1_out);
    t->Branch("eleTrkPt_1", &eleTrkPt_1_out);
    t->Branch("eleTrkEta_1", &eleTrkEta_1_out);
    t->Branch("eleTrkPhi_1", &eleTrkPhi_1_out);
    t->Branch("eleTrkCharge_1", &eleTrkCharge_1_out);
    t->Branch("eleTrkChi2_1", &eleTrkChi2_1_out);
    t->Branch("eleTrkNdof_1", &eleTrkNdof_1_out);
    t->Branch("eleTrkNormalizedChi2_1", &eleTrkNormalizedChi2_1_out);
    t->Branch("elePt_1", &elePt_1_out);
    t->Branch("eleEta_1", &eleEta_1_out);
    t->Branch("elePhi_1", &elePhi_1_out);
    t->Branch("eleSCEn_1", &eleSCEn_1_out);
    t->Branch("eleESEn_1", &eleESEn_1_out);
    t->Branch("eleSCEta_1", &eleSCEta_1_out);
    t->Branch("eleSCPhi_1", &eleSCPhi_1_out);
    t->Branch("eleSCRawEn_1", &eleSCRawEn_1_out);
    t->Branch("eleSCEtaWidth_1", &eleSCEtaWidth_1_out);
    t->Branch("eleSCPhiWidth_1", &eleSCPhiWidth_1_out);
    t->Branch("eleHoverE_1", &eleHoverE_1_out);
    t->Branch("eleEoverP_1", &eleEoverP_1_out);
    t->Branch("eleEoverPInv_1", &eleEoverPInv_1_out);
    t->Branch("eleBrem_1", &eleBrem_1_out);
    t->Branch("eledEtaAtVtx_1", &eledEtaAtVtx_1_out);
    t->Branch("eledPhiAtVtx_1", &eledPhiAtVtx_1_out);
    t->Branch("eleSigmaIEtaIEta_1", &eleSigmaIEtaIEta_1_out);
    t->Branch("eleSigmaIEtaIEta_2012_1", &eleSigmaIEtaIEta_2012_1_out);
    t->Branch("eleSigmaIPhiIPhi_1", &eleSigmaIPhiIPhi_1_out);
    t->Branch("eleMissHits_1", &eleMissHits_1_out);
    t->Branch("eleESEffSigmaRR_1", &eleESEffSigmaRR_1_out);
    t->Branch("elePFChIso_1", &elePFChIso_1_out);
    t->Branch("elePFPhoIso_1", &elePFPhoIso_1_out);
    t->Branch("elePFNeuIso_1", &elePFNeuIso_1_out);
    t->Branch("elePFPUIso_1", &elePFPUIso_1_out);
    t->Branch("eleBC1E_1", &eleBC1E_1_out);
    t->Branch("eleBC1Eta_1", &eleBC1Eta_1_out);
    t->Branch("eleBC2E_1", &eleBC2E_1_out);
    t->Branch("eleBC2Eta_1", &eleBC2Eta_1_out);

    t->Branch("eleCharge_2", &eleCharge_2_out);
    t->Branch("eleChargeConsistent_2", &eleChargeConsistent_2_out);
    t->Branch("eleEn_2", &eleEn_2_out);
    t->Branch("eleD0_2", &eleD0_2_out);
    t->Branch("eleDz_2", &eleDz_2_out);
    t->Branch("eleD0Err_2", &eleD0Err_2_out);
    t->Branch("eleDzErr_2", &eleDzErr_2_out);
    t->Branch("eleTrkPt_2", &eleTrkPt_2_out);
    t->Branch("eleTrkEta_2", &eleTrkEta_2_out);
    t->Branch("eleTrkPhi_2", &eleTrkPhi_2_out);
    t->Branch("eleTrkCharge_2", &eleTrkCharge_2_out);
    t->Branch("eleTrkChi2_2", &eleTrkChi2_2_out);
    t->Branch("eleTrkNdof_2", &eleTrkNdof_2_out);
    t->Branch("eleTrkNormalizedChi2_2", &eleTrkNormalizedChi2_2_out);
    t->Branch("elePt_2", &elePt_2_out);
    t->Branch("eleEta_2", &eleEta_2_out);
    t->Branch("elePhi_2", &elePhi_2_out);
    t->Branch("eleSCEn_2", &eleSCEn_2_out);
    t->Branch("eleESEn_2", &eleESEn_2_out);
    t->Branch("eleSCEta_2", &eleSCEta_2_out);
    t->Branch("eleSCPhi_2", &eleSCPhi_2_out);
    t->Branch("eleSCRawEn_2", &eleSCRawEn_2_out);
    t->Branch("eleSCEtaWidth_2", &eleSCEtaWidth_2_out);
    t->Branch("eleSCPhiWidth_2", &eleSCPhiWidth_2_out);
    t->Branch("eleHoverE_2", &eleHoverE_2_out);
    t->Branch("eleEoverP_2", &eleEoverP_2_out);
    t->Branch("eleEoverPInv_2", &eleEoverPInv_2_out);
    t->Branch("eleBrem_2", &eleBrem_2_out);
    t->Branch("eledEtaAtVtx_2", &eledEtaAtVtx_2_out);
    t->Branch("eledPhiAtVtx_2", &eledPhiAtVtx_2_out);
    t->Branch("eleSigmaIEtaIEta_2", &eleSigmaIEtaIEta_2_out);
    t->Branch("eleSigmaIEtaIEta_2012_2", &eleSigmaIEtaIEta_2012_2_out);
    t->Branch("eleSigmaIPhiIPhi_2", &eleSigmaIPhiIPhi_2_out);
    t->Branch("eleMissHits_2", &eleMissHits_2_out);
    t->Branch("eleESEffSigmaRR_2", &eleESEffSigmaRR_2_out);
    t->Branch("elePFChIso_2", &elePFChIso_2_out);
    t->Branch("elePFPhoIso_2", &elePFPhoIso_2_out);
    t->Branch("elePFNeuIso_2", &elePFNeuIso_2_out);
    t->Branch("elePFPUIso_2", &elePFPUIso_2_out);
    t->Branch("eleBC1E_2", &eleBC1E_2_out);
    t->Branch("eleBC1Eta_2", &eleBC1Eta_2_out);
    t->Branch("eleBC2E_2", &eleBC2E_2_out);
    t->Branch("eleBC2Eta_2", &eleBC2Eta_2_out);

    t->Branch("diEleM", &diEleM_out);
    t->Branch("diEleEn", &diEleEn_out);
    t->Branch("diElePt", &diElePt_out);
    t->Branch("diEleEta", &diEleEta_out);
    t->Branch("diElePhi", &diElePhi_out);
}

void dielectron::makeDiElectronPairs(ggHiNtuplizer &tggHiNtuplizer, bool doSizeCheck)
{
    eleCharge_1_out.clear();
    eleChargeConsistent_1_out.clear();
    eleEn_1_out.clear();
    eleD0_1_out.clear();
    eleDz_1_out.clear();
    eleD0Err_1_out.clear();
    eleDzErr_1_out.clear();
    eleTrkPt_1_out.clear();
    eleTrkEta_1_out.clear();
    eleTrkPhi_1_out.clear();
    eleTrkCharge_1_out.clear();
    eleTrkChi2_1_out.clear();
    eleTrkNdof_1_out.clear();
    eleTrkNormalizedChi2_1_out.clear();
    elePt_1_out.clear();
    eleEta_1_out.clear();
    elePhi_1_out.clear();
    eleSCEn_1_out.clear();
    eleESEn_1_out.clear();
    eleSCEta_1_out.clear();
    eleSCPhi_1_out.clear();
    eleSCRawEn_1_out.clear();
    eleSCEtaWidth_1_out.clear();
    eleSCPhiWidth_1_out.clear();
    eleHoverE_1_out.clear();
    eleEoverP_1_out.clear();
    eleEoverPInv_1_out.clear();
    eleBrem_1_out.clear();
    eledEtaAtVtx_1_out.clear();
    eledPhiAtVtx_1_out.clear();
    eleSigmaIEtaIEta_1_out.clear();
    eleSigmaIEtaIEta_2012_1_out.clear();
    eleSigmaIPhiIPhi_1_out.clear();
    eleMissHits_1_out.clear();
    eleESEffSigmaRR_1_out.clear();
    elePFChIso_1_out.clear();
    elePFPhoIso_1_out.clear();
    elePFNeuIso_1_out.clear();
    elePFPUIso_1_out.clear();
    eleBC1E_1_out.clear();
    eleBC1Eta_1_out.clear();
    eleBC2E_1_out.clear();
    eleBC2Eta_1_out.clear();

    eleCharge_2_out.clear();
    eleChargeConsistent_2_out.clear();
    eleEn_2_out.clear();
    eleD0_2_out.clear();
    eleDz_2_out.clear();
    eleD0Err_2_out.clear();
    eleDzErr_2_out.clear();
    eleTrkPt_2_out.clear();
    eleTrkEta_2_out.clear();
    eleTrkPhi_2_out.clear();
    eleTrkCharge_2_out.clear();
    eleTrkChi2_2_out.clear();
    eleTrkNdof_2_out.clear();
    eleTrkNormalizedChi2_2_out.clear();
    elePt_2_out.clear();
    eleEta_2_out.clear();
    elePhi_2_out.clear();
    eleSCEn_2_out.clear();
    eleESEn_2_out.clear();
    eleSCEta_2_out.clear();
    eleSCPhi_2_out.clear();
    eleSCRawEn_2_out.clear();
    eleSCEtaWidth_2_out.clear();
    eleSCPhiWidth_2_out.clear();
    eleHoverE_2_out.clear();
    eleEoverP_2_out.clear();
    eleEoverPInv_2_out.clear();
    eleBrem_2_out.clear();
    eledEtaAtVtx_2_out.clear();
    eledPhiAtVtx_2_out.clear();
    eleSigmaIEtaIEta_2_out.clear();
    eleSigmaIEtaIEta_2012_2_out.clear();
    eleSigmaIPhiIPhi_2_out.clear();
    eleMissHits_2_out.clear();
    eleESEffSigmaRR_2_out.clear();
    elePFChIso_2_out.clear();
    elePFPhoIso_2_out.clear();
    elePFNeuIso_2_out.clear();
    elePFPUIso_2_out.clear();
    eleBC1E_2_out.clear();
    eleBC1Eta_2_out.clear();
    eleBC2E_2_out.clear();
    eleBC2Eta_2_out.clear();

    diEleM_out.clear();
    diEleEn_out.clear();
    diElePt_out.clear();
    diEleEta_out.clear();
    diElePhi_out.clear();

    nEle_out = tggHiNtuplizer.nEle;
    for(int i=0; i<nEle_out; ++i)
    {
        for(int j=i+1; j<nEle_out; ++j)
        {
            if (doSizeCheck) {

                if(tggHiNtuplizer.eleCharge->size() == (unsigned)nEle_out)  eleCharge_1_out.push_back(tggHiNtuplizer.eleCharge->at(i));
                if(tggHiNtuplizer.eleChargeConsistent->size() == (unsigned)nEle_out)  eleChargeConsistent_1_out.push_back(tggHiNtuplizer.eleChargeConsistent->at(i));
                if(tggHiNtuplizer.eleEn->size() == (unsigned)nEle_out)  eleEn_1_out.push_back(tggHiNtuplizer.eleEn->at(i));
                if(tggHiNtuplizer.eleD0->size() == (unsigned)nEle_out)  eleD0_1_out.push_back(tggHiNtuplizer.eleD0->at(i));
                if(tggHiNtuplizer.eleDz->size() == (unsigned)nEle_out)  eleDz_1_out.push_back(tggHiNtuplizer.eleDz->at(i));
                if(tggHiNtuplizer.eleD0Err->size() == (unsigned)nEle_out)  eleD0Err_1_out.push_back(tggHiNtuplizer.eleD0Err->at(i));
                if(tggHiNtuplizer.eleDzErr->size() == (unsigned)nEle_out)  eleDzErr_1_out.push_back(tggHiNtuplizer.eleDzErr->at(i));
                if(tggHiNtuplizer.eleTrkPt->size() == (unsigned)nEle_out)  eleTrkPt_1_out.push_back(tggHiNtuplizer.eleTrkPt->at(i));
                if(tggHiNtuplizer.eleTrkEta->size() == (unsigned)nEle_out)  eleTrkEta_1_out.push_back(tggHiNtuplizer.eleTrkEta->at(i));
                if(tggHiNtuplizer.eleTrkPhi->size() == (unsigned)nEle_out)  eleTrkPhi_1_out.push_back(tggHiNtuplizer.eleTrkPhi->at(i));
                if(tggHiNtuplizer.eleTrkCharge->size() == (unsigned)nEle_out)  eleTrkCharge_1_out.push_back(tggHiNtuplizer.eleTrkCharge->at(i));
                if(tggHiNtuplizer.eleTrkChi2->size() == (unsigned)nEle_out)  eleTrkChi2_1_out.push_back(tggHiNtuplizer.eleTrkChi2->at(i));
                if(tggHiNtuplizer.eleTrkNdof->size() == (unsigned)nEle_out)  eleTrkNdof_1_out.push_back(tggHiNtuplizer.eleTrkNdof->at(i));
                if(tggHiNtuplizer.eleTrkNormalizedChi2->size() == (unsigned)nEle_out)  eleTrkNormalizedChi2_1_out.push_back(tggHiNtuplizer.eleTrkNormalizedChi2->at(i));
                if(tggHiNtuplizer.elePt->size() == (unsigned)nEle_out)  elePt_1_out.push_back(tggHiNtuplizer.elePt->at(i));
                if(tggHiNtuplizer.eleEta->size() == (unsigned)nEle_out)  eleEta_1_out.push_back(tggHiNtuplizer.eleEta->at(i));
                if(tggHiNtuplizer.elePhi->size() == (unsigned)nEle_out)  elePhi_1_out.push_back(tggHiNtuplizer.elePhi->at(i));
                if(tggHiNtuplizer.eleSCEn->size() == (unsigned)nEle_out)  eleSCEn_1_out.push_back(tggHiNtuplizer.eleSCEn->at(i));
                if(tggHiNtuplizer.eleESEn->size() == (unsigned)nEle_out)  eleESEn_1_out.push_back(tggHiNtuplizer.eleESEn->at(i));
                if(tggHiNtuplizer.eleSCEta->size() == (unsigned)nEle_out)  eleSCEta_1_out.push_back(tggHiNtuplizer.eleSCEta->at(i));
                if(tggHiNtuplizer.eleSCPhi->size() == (unsigned)nEle_out)  eleSCPhi_1_out.push_back(tggHiNtuplizer.eleSCPhi->at(i));
                if(tggHiNtuplizer.eleSCRawEn->size() == (unsigned)nEle_out)  eleSCRawEn_1_out.push_back(tggHiNtuplizer.eleSCRawEn->at(i));
                if(tggHiNtuplizer.eleSCEtaWidth->size() == (unsigned)nEle_out)  eleSCEtaWidth_1_out.push_back(tggHiNtuplizer.eleSCEtaWidth->at(i));
                if(tggHiNtuplizer.eleSCPhiWidth->size() == (unsigned)nEle_out)  eleSCPhiWidth_1_out.push_back(tggHiNtuplizer.eleSCPhiWidth->at(i));
                if(tggHiNtuplizer.eleHoverE->size() == (unsigned)nEle_out)  eleHoverE_1_out.push_back(tggHiNtuplizer.eleHoverE->at(i));
                if(tggHiNtuplizer.eleEoverP->size() == (unsigned)nEle_out)  eleEoverP_1_out.push_back(tggHiNtuplizer.eleEoverP->at(i));
                if(tggHiNtuplizer.eleEoverPInv->size() == (unsigned)nEle_out)  eleEoverPInv_1_out.push_back(tggHiNtuplizer.eleEoverPInv->at(i));
                if(tggHiNtuplizer.eleBrem->size() == (unsigned)nEle_out)  eleBrem_1_out.push_back(tggHiNtuplizer.eleBrem->at(i));
                if(tggHiNtuplizer.eledEtaAtVtx->size() == (unsigned)nEle_out)  eledEtaAtVtx_1_out.push_back(tggHiNtuplizer.eledEtaAtVtx->at(i));
                if(tggHiNtuplizer.eledPhiAtVtx->size() == (unsigned)nEle_out)  eledPhiAtVtx_1_out.push_back(tggHiNtuplizer.eledPhiAtVtx->at(i));
                if(tggHiNtuplizer.eleSigmaIEtaIEta->size() == (unsigned)nEle_out)  eleSigmaIEtaIEta_1_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta->at(i));
                if(tggHiNtuplizer.eleSigmaIEtaIEta_2012->size() == (unsigned)nEle_out)  eleSigmaIEtaIEta_2012_1_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta_2012->at(i));
                if(tggHiNtuplizer.eleSigmaIPhiIPhi->size() == (unsigned)nEle_out)  eleSigmaIPhiIPhi_1_out.push_back(tggHiNtuplizer.eleSigmaIPhiIPhi->at(i));
                if(tggHiNtuplizer.eleMissHits->size() == (unsigned)nEle_out)  eleMissHits_1_out.push_back(tggHiNtuplizer.eleMissHits->at(i));
                if(tggHiNtuplizer.eleESEffSigmaRR->size() == (unsigned)nEle_out)  eleESEffSigmaRR_1_out.push_back(tggHiNtuplizer.eleESEffSigmaRR->at(i));
                if(tggHiNtuplizer.elePFChIso->size() == (unsigned)nEle_out)  elePFChIso_1_out.push_back(tggHiNtuplizer.elePFChIso->at(i));
                if(tggHiNtuplizer.elePFPhoIso->size() == (unsigned)nEle_out)  elePFPhoIso_1_out.push_back(tggHiNtuplizer.elePFPhoIso->at(i));
                if(tggHiNtuplizer.elePFNeuIso->size() == (unsigned)nEle_out)  elePFNeuIso_1_out.push_back(tggHiNtuplizer.elePFNeuIso->at(i));
                if(tggHiNtuplizer.elePFPUIso->size() == (unsigned)nEle_out)  elePFPUIso_1_out.push_back(tggHiNtuplizer.elePFPUIso->at(i));
                if(tggHiNtuplizer.eleBC1E->size() == (unsigned)nEle_out)  eleBC1E_1_out.push_back(tggHiNtuplizer.eleBC1E->at(i));
                if(tggHiNtuplizer.eleBC1Eta->size() == (unsigned)nEle_out)  eleBC1Eta_1_out.push_back(tggHiNtuplizer.eleBC1Eta->at(i));
                if(tggHiNtuplizer.eleBC2E->size() == (unsigned)nEle_out)  eleBC2E_1_out.push_back(tggHiNtuplizer.eleBC2E->at(i));
                if(tggHiNtuplizer.eleBC2Eta->size() == (unsigned)nEle_out)  eleBC2Eta_1_out.push_back(tggHiNtuplizer.eleBC2Eta->at(i));

                if(tggHiNtuplizer.eleCharge->size() == (unsigned)nEle_out)  eleCharge_2_out.push_back(tggHiNtuplizer.eleCharge->at(j));
                if(tggHiNtuplizer.eleChargeConsistent->size() == (unsigned)nEle_out)  eleChargeConsistent_2_out.push_back(tggHiNtuplizer.eleChargeConsistent->at(j));
                if(tggHiNtuplizer.eleEn->size() == (unsigned)nEle_out)  eleEn_2_out.push_back(tggHiNtuplizer.eleEn->at(j));
                if(tggHiNtuplizer.eleD0->size() == (unsigned)nEle_out)  eleD0_2_out.push_back(tggHiNtuplizer.eleD0->at(j));
                if(tggHiNtuplizer.eleDz->size() == (unsigned)nEle_out)  eleDz_2_out.push_back(tggHiNtuplizer.eleDz->at(j));
                if(tggHiNtuplizer.eleD0Err->size() == (unsigned)nEle_out)  eleD0Err_2_out.push_back(tggHiNtuplizer.eleD0Err->at(j));
                if(tggHiNtuplizer.eleDzErr->size() == (unsigned)nEle_out)  eleDzErr_2_out.push_back(tggHiNtuplizer.eleDzErr->at(j));
                if(tggHiNtuplizer.eleTrkPt->size() == (unsigned)nEle_out)  eleTrkPt_2_out.push_back(tggHiNtuplizer.eleTrkPt->at(j));
                if(tggHiNtuplizer.eleTrkEta->size() == (unsigned)nEle_out)  eleTrkEta_2_out.push_back(tggHiNtuplizer.eleTrkEta->at(j));
                if(tggHiNtuplizer.eleTrkPhi->size() == (unsigned)nEle_out)  eleTrkPhi_2_out.push_back(tggHiNtuplizer.eleTrkPhi->at(j));
                if(tggHiNtuplizer.eleTrkCharge->size() == (unsigned)nEle_out)  eleTrkCharge_2_out.push_back(tggHiNtuplizer.eleTrkCharge->at(j));
                if(tggHiNtuplizer.eleTrkChi2->size() == (unsigned)nEle_out)  eleTrkChi2_2_out.push_back(tggHiNtuplizer.eleTrkChi2->at(j));
                if(tggHiNtuplizer.eleTrkNdof->size() == (unsigned)nEle_out)  eleTrkNdof_2_out.push_back(tggHiNtuplizer.eleTrkNdof->at(j));
                if(tggHiNtuplizer.eleTrkNormalizedChi2->size() == (unsigned)nEle_out)  eleTrkNormalizedChi2_2_out.push_back(tggHiNtuplizer.eleTrkNormalizedChi2->at(j));
                if(tggHiNtuplizer.elePt->size() == (unsigned)nEle_out)  elePt_2_out.push_back(tggHiNtuplizer.elePt->at(j));
                if(tggHiNtuplizer.eleEta->size() == (unsigned)nEle_out)  eleEta_2_out.push_back(tggHiNtuplizer.eleEta->at(j));
                if(tggHiNtuplizer.elePhi->size() == (unsigned)nEle_out)  elePhi_2_out.push_back(tggHiNtuplizer.elePhi->at(j));
                if(tggHiNtuplizer.eleSCEn->size() == (unsigned)nEle_out)  eleSCEn_2_out.push_back(tggHiNtuplizer.eleSCEn->at(j));
                if(tggHiNtuplizer.eleESEn->size() == (unsigned)nEle_out)  eleESEn_2_out.push_back(tggHiNtuplizer.eleESEn->at(j));
                if(tggHiNtuplizer.eleSCEta->size() == (unsigned)nEle_out)  eleSCEta_2_out.push_back(tggHiNtuplizer.eleSCEta->at(j));
                if(tggHiNtuplizer.eleSCPhi->size() == (unsigned)nEle_out)  eleSCPhi_2_out.push_back(tggHiNtuplizer.eleSCPhi->at(j));
                if(tggHiNtuplizer.eleSCRawEn->size() == (unsigned)nEle_out)  eleSCRawEn_2_out.push_back(tggHiNtuplizer.eleSCRawEn->at(j));
                if(tggHiNtuplizer.eleSCEtaWidth->size() == (unsigned)nEle_out)  eleSCEtaWidth_2_out.push_back(tggHiNtuplizer.eleSCEtaWidth->at(j));
                if(tggHiNtuplizer.eleSCPhiWidth->size() == (unsigned)nEle_out)  eleSCPhiWidth_2_out.push_back(tggHiNtuplizer.eleSCPhiWidth->at(j));
                if(tggHiNtuplizer.eleHoverE->size() == (unsigned)nEle_out)  eleHoverE_2_out.push_back(tggHiNtuplizer.eleHoverE->at(j));
                if(tggHiNtuplizer.eleEoverP->size() == (unsigned)nEle_out)  eleEoverP_2_out.push_back(tggHiNtuplizer.eleEoverP->at(j));
                if(tggHiNtuplizer.eleEoverPInv->size() == (unsigned)nEle_out)  eleEoverPInv_2_out.push_back(tggHiNtuplizer.eleEoverPInv->at(j));
                if(tggHiNtuplizer.eleBrem->size() == (unsigned)nEle_out)  eleBrem_2_out.push_back(tggHiNtuplizer.eleBrem->at(j));
                if(tggHiNtuplizer.eledEtaAtVtx->size() == (unsigned)nEle_out)  eledEtaAtVtx_2_out.push_back(tggHiNtuplizer.eledEtaAtVtx->at(j));
                if(tggHiNtuplizer.eledPhiAtVtx->size() == (unsigned)nEle_out)  eledPhiAtVtx_2_out.push_back(tggHiNtuplizer.eledPhiAtVtx->at(j));
                if(tggHiNtuplizer.eleSigmaIEtaIEta->size() == (unsigned)nEle_out)  eleSigmaIEtaIEta_2_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta->at(j));
                if(tggHiNtuplizer.eleSigmaIEtaIEta_2012->size() == (unsigned)nEle_out)  eleSigmaIEtaIEta_2012_2_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta_2012->at(j));
                if(tggHiNtuplizer.eleSigmaIPhiIPhi->size() == (unsigned)nEle_out)  eleSigmaIPhiIPhi_2_out.push_back(tggHiNtuplizer.eleSigmaIPhiIPhi->at(j));
                if(tggHiNtuplizer.eleMissHits->size() == (unsigned)nEle_out)  eleMissHits_2_out.push_back(tggHiNtuplizer.eleMissHits->at(j));
                if(tggHiNtuplizer.eleESEffSigmaRR->size() == (unsigned)nEle_out)  eleESEffSigmaRR_2_out.push_back(tggHiNtuplizer.eleESEffSigmaRR->at(j));
                if(tggHiNtuplizer.elePFChIso->size() == (unsigned)nEle_out)  elePFChIso_2_out.push_back(tggHiNtuplizer.elePFChIso->at(j));
                if(tggHiNtuplizer.elePFPhoIso->size() == (unsigned)nEle_out)  elePFPhoIso_2_out.push_back(tggHiNtuplizer.elePFPhoIso->at(j));
                if(tggHiNtuplizer.elePFNeuIso->size() == (unsigned)nEle_out)  elePFNeuIso_2_out.push_back(tggHiNtuplizer.elePFNeuIso->at(j));
                if(tggHiNtuplizer.elePFPUIso->size() == (unsigned)nEle_out)  elePFPUIso_2_out.push_back(tggHiNtuplizer.elePFPUIso->at(j));
                if(tggHiNtuplizer.eleBC1E->size() == (unsigned)nEle_out)  eleBC1E_2_out.push_back(tggHiNtuplizer.eleBC1E->at(j));
                if(tggHiNtuplizer.eleBC1Eta->size() == (unsigned)nEle_out)  eleBC1Eta_2_out.push_back(tggHiNtuplizer.eleBC1Eta->at(j));
                if(tggHiNtuplizer.eleBC2E->size() == (unsigned)nEle_out)  eleBC2E_2_out.push_back(tggHiNtuplizer.eleBC2E->at(j));
                if(tggHiNtuplizer.eleBC2Eta->size() == (unsigned)nEle_out)  eleBC2Eta_2_out.push_back(tggHiNtuplizer.eleBC2Eta->at(j));

                // dielectron
                if (tggHiNtuplizer.elePt->size()  == (unsigned)nEle_out &&
                    tggHiNtuplizer.eleEta->size() == (unsigned)nEle_out &&
                    tggHiNtuplizer.elePhi->size() == (unsigned)nEle_out)
                {
                    TLorentzVector v1, v2, vSum;
                    v1.SetPtEtaPhiM( tggHiNtuplizer.elePt->at(i), tggHiNtuplizer.eleEta->at(i),
                            tggHiNtuplizer.elePhi->at(i), mass);
                    v2.SetPtEtaPhiM( tggHiNtuplizer.elePt->at(j), tggHiNtuplizer.eleEta->at(j),
                            tggHiNtuplizer.elePhi->at(j), mass);
                    vSum = v1+v2;

                    diEleM_out.push_back(vSum.M());
                    diEleEn_out.push_back(vSum.Energy());
                    diElePt_out.push_back(vSum.Pt());
                    diEleEta_out.push_back(vSum.Eta());
                    diElePhi_out.push_back(vSum.Phi());
                }
            }
            else {
                eleCharge_1_out.push_back(tggHiNtuplizer.eleCharge->at(i));
                eleChargeConsistent_1_out.push_back(tggHiNtuplizer.eleChargeConsistent->at(i));
                eleEn_1_out.push_back(tggHiNtuplizer.eleEn->at(i));
                eleD0_1_out.push_back(tggHiNtuplizer.eleD0->at(i));
                eleDz_1_out.push_back(tggHiNtuplizer.eleDz->at(i));
                eleD0Err_1_out.push_back(tggHiNtuplizer.eleD0Err->at(i));
                eleDzErr_1_out.push_back(tggHiNtuplizer.eleDzErr->at(i));
                eleTrkPt_1_out.push_back(tggHiNtuplizer.eleTrkPt->at(i));
                eleTrkEta_1_out.push_back(tggHiNtuplizer.eleTrkEta->at(i));
                eleTrkPhi_1_out.push_back(tggHiNtuplizer.eleTrkPhi->at(i));
                eleTrkCharge_1_out.push_back(tggHiNtuplizer.eleTrkCharge->at(i));
                eleTrkChi2_1_out.push_back(tggHiNtuplizer.eleTrkChi2->at(i));
                eleTrkNdof_1_out.push_back(tggHiNtuplizer.eleTrkNdof->at(i));
                eleTrkNormalizedChi2_1_out.push_back(tggHiNtuplizer.eleTrkNormalizedChi2->at(i));
                elePt_1_out.push_back(tggHiNtuplizer.elePt->at(i));
                eleEta_1_out.push_back(tggHiNtuplizer.eleEta->at(i));
                elePhi_1_out.push_back(tggHiNtuplizer.elePhi->at(i));
                eleSCEn_1_out.push_back(tggHiNtuplizer.eleSCEn->at(i));
                eleESEn_1_out.push_back(tggHiNtuplizer.eleESEn->at(i));
                eleSCEta_1_out.push_back(tggHiNtuplizer.eleSCEta->at(i));
                eleSCPhi_1_out.push_back(tggHiNtuplizer.eleSCPhi->at(i));
                eleSCRawEn_1_out.push_back(tggHiNtuplizer.eleSCRawEn->at(i));
                eleSCEtaWidth_1_out.push_back(tggHiNtuplizer.eleSCEtaWidth->at(i));
                eleSCPhiWidth_1_out.push_back(tggHiNtuplizer.eleSCPhiWidth->at(i));
                eleHoverE_1_out.push_back(tggHiNtuplizer.eleHoverE->at(i));
                eleEoverP_1_out.push_back(tggHiNtuplizer.eleEoverP->at(i));
                eleEoverPInv_1_out.push_back(tggHiNtuplizer.eleEoverPInv->at(i));
                eleBrem_1_out.push_back(tggHiNtuplizer.eleBrem->at(i));
                eledEtaAtVtx_1_out.push_back(tggHiNtuplizer.eledEtaAtVtx->at(i));
                eledPhiAtVtx_1_out.push_back(tggHiNtuplizer.eledPhiAtVtx->at(i));
                eleSigmaIEtaIEta_1_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta->at(i));
                eleSigmaIEtaIEta_2012_1_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta_2012->at(i));
                eleSigmaIPhiIPhi_1_out.push_back(tggHiNtuplizer.eleSigmaIPhiIPhi->at(i));
                eleMissHits_1_out.push_back(tggHiNtuplizer.eleMissHits->at(i));
                eleESEffSigmaRR_1_out.push_back(tggHiNtuplizer.eleESEffSigmaRR->at(i));
                elePFChIso_1_out.push_back(tggHiNtuplizer.elePFChIso->at(i));
                elePFPhoIso_1_out.push_back(tggHiNtuplizer.elePFPhoIso->at(i));
                elePFNeuIso_1_out.push_back(tggHiNtuplizer.elePFNeuIso->at(i));
                elePFPUIso_1_out.push_back(tggHiNtuplizer.elePFPUIso->at(i));
                eleBC1E_1_out.push_back(tggHiNtuplizer.eleBC1E->at(i));
                eleBC1Eta_1_out.push_back(tggHiNtuplizer.eleBC1Eta->at(i));
                eleBC2E_1_out.push_back(tggHiNtuplizer.eleBC2E->at(i));
                eleBC2Eta_1_out.push_back(tggHiNtuplizer.eleBC2Eta->at(i));

                eleCharge_2_out.push_back(tggHiNtuplizer.eleCharge->at(j));
                eleChargeConsistent_2_out.push_back(tggHiNtuplizer.eleChargeConsistent->at(j));
                eleEn_2_out.push_back(tggHiNtuplizer.eleEn->at(j));
                eleD0_2_out.push_back(tggHiNtuplizer.eleD0->at(j));
                eleDz_2_out.push_back(tggHiNtuplizer.eleDz->at(j));
                eleD0Err_2_out.push_back(tggHiNtuplizer.eleD0Err->at(j));
                eleDzErr_2_out.push_back(tggHiNtuplizer.eleDzErr->at(j));
                eleTrkPt_2_out.push_back(tggHiNtuplizer.eleTrkPt->at(j));
                eleTrkEta_2_out.push_back(tggHiNtuplizer.eleTrkEta->at(j));
                eleTrkPhi_2_out.push_back(tggHiNtuplizer.eleTrkPhi->at(j));
                eleTrkCharge_2_out.push_back(tggHiNtuplizer.eleTrkCharge->at(j));
                eleTrkChi2_2_out.push_back(tggHiNtuplizer.eleTrkChi2->at(j));
                eleTrkNdof_2_out.push_back(tggHiNtuplizer.eleTrkNdof->at(j));
                eleTrkNormalizedChi2_2_out.push_back(tggHiNtuplizer.eleTrkNormalizedChi2->at(j));
                elePt_2_out.push_back(tggHiNtuplizer.elePt->at(j));
                eleEta_2_out.push_back(tggHiNtuplizer.eleEta->at(j));
                elePhi_2_out.push_back(tggHiNtuplizer.elePhi->at(j));
                eleSCEn_2_out.push_back(tggHiNtuplizer.eleSCEn->at(j));
                eleESEn_2_out.push_back(tggHiNtuplizer.eleESEn->at(j));
                eleSCEta_2_out.push_back(tggHiNtuplizer.eleSCEta->at(j));
                eleSCPhi_2_out.push_back(tggHiNtuplizer.eleSCPhi->at(j));
                eleSCRawEn_2_out.push_back(tggHiNtuplizer.eleSCRawEn->at(j));
                eleSCEtaWidth_2_out.push_back(tggHiNtuplizer.eleSCEtaWidth->at(j));
                eleSCPhiWidth_2_out.push_back(tggHiNtuplizer.eleSCPhiWidth->at(j));
                eleHoverE_2_out.push_back(tggHiNtuplizer.eleHoverE->at(j));
                eleEoverP_2_out.push_back(tggHiNtuplizer.eleEoverP->at(j));
                eleEoverPInv_2_out.push_back(tggHiNtuplizer.eleEoverPInv->at(j));
                eleBrem_2_out.push_back(tggHiNtuplizer.eleBrem->at(j));
                eledEtaAtVtx_2_out.push_back(tggHiNtuplizer.eledEtaAtVtx->at(j));
                eledPhiAtVtx_2_out.push_back(tggHiNtuplizer.eledPhiAtVtx->at(j));
                eleSigmaIEtaIEta_2_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta->at(j));
                eleSigmaIEtaIEta_2012_2_out.push_back(tggHiNtuplizer.eleSigmaIEtaIEta_2012->at(j));
                eleSigmaIPhiIPhi_2_out.push_back(tggHiNtuplizer.eleSigmaIPhiIPhi->at(j));
                eleMissHits_2_out.push_back(tggHiNtuplizer.eleMissHits->at(j));
                eleESEffSigmaRR_2_out.push_back(tggHiNtuplizer.eleESEffSigmaRR->at(j));
                elePFChIso_2_out.push_back(tggHiNtuplizer.elePFChIso->at(j));
                elePFPhoIso_2_out.push_back(tggHiNtuplizer.elePFPhoIso->at(j));
                elePFNeuIso_2_out.push_back(tggHiNtuplizer.elePFNeuIso->at(j));
                elePFPUIso_2_out.push_back(tggHiNtuplizer.elePFPUIso->at(j));
                eleBC1E_2_out.push_back(tggHiNtuplizer.eleBC1E->at(j));
                eleBC1Eta_2_out.push_back(tggHiNtuplizer.eleBC1Eta->at(j));
                eleBC2E_2_out.push_back(tggHiNtuplizer.eleBC2E->at(j));
                eleBC2Eta_2_out.push_back(tggHiNtuplizer.eleBC2Eta->at(j));

                // dielectron
                TLorentzVector v1, v2, vSum;
                v1.SetPtEtaPhiM( tggHiNtuplizer.elePt->at(i), tggHiNtuplizer.eleEta->at(i),
                        tggHiNtuplizer.elePhi->at(i), mass);
                v2.SetPtEtaPhiM( tggHiNtuplizer.elePt->at(j), tggHiNtuplizer.eleEta->at(j),
                        tggHiNtuplizer.elePhi->at(j), mass);
                vSum = v1+v2;

                diEleM_out.push_back(vSum.M());
                diEleEn_out.push_back(vSum.Energy());
                diElePt_out.push_back(vSum.Pt());
                diEleEta_out.push_back(vSum.Eta());
                diElePhi_out.push_back(vSum.Phi());
            }
        }
    }
}

#endif /* TREEHEADERS_DIELECTRONTREE_H_ */
