/*
 * diphotonTree.h
 *
 *      Author: Kaya Tatar
 *
 *       class to manage diphoton tree, tree of photon pairs that match to an electron
 */

#ifndef TREEHEADERS_DIPHOTONTREE_H_
#define TREEHEADERS_DIPHOTONTREE_H_

#include <TLorentzVector.h>

#include <vector>

#include "ggHiNtuplizerTree.h"

class diphoton {
public :
    diphoton(){

        cutDeltaR = 0.15;

        phoE_1 = 0;
        phoEt_1 = 0;
        phoEta_1 = 0;
        phoPhi_1 = 0;
        phoSCE_1 = 0;
        phoSCRawE_1 = 0;
        phoESEn_1 = 0;
        phoSCEta_1 = 0;
        phoSCPhi_1 = 0;
        phoSCEtaWidth_1 = 0;
        phoSCPhiWidth_1 = 0;
        phoSCBrem_1 = 0;
        phohasPixelSeed_1 = 0;
        phoR9_1 = 0;
        phoHoverE_1 = 0;
        phoSigmaIEtaIEta_1 = 0;
        phoE1x3_1 = 0;
        phoE2x2_1 = 0;
        phoE3x3_1 = 0;
        phoE2x5Max_1 = 0;
        phoE1x5_1 = 0;
        phoE2x5_1 = 0;
        phoE5x5_1 = 0;
        phoMaxEnergyXtal_1 = 0;
        phoSigmaEtaEta_1 = 0;
        phoR1x5_1 = 0;
        phoR2x5_1 = 0;
        phoESEffSigmaRR_1 = 0;
        phoSigmaIEtaIEta_2012_1 = 0;
        phoSigmaIEtaIPhi_2012_1 = 0;
        phoSigmaIPhiIPhi_2012_1 = 0;
        phoE1x3_2012_1 = 0;
        phoE2x2_2012_1 = 0;
        phoE3x3_2012_1 = 0;
        phoE2x5Max_2012_1 = 0;
        phoE5x5_2012_1 = 0;
        phoBC1E_1 = 0;
        phoBC1Eta_1 = 0;
        phoBC2E_1 = 0;
        phoBC2Eta_1 = 0;
        pho_ecalClusterIsoR2_1 = 0;
        pho_ecalClusterIsoR3_1 = 0;
        pho_ecalClusterIsoR4_1 = 0;
        pho_ecalClusterIsoR5_1 = 0;
        pho_hcalRechitIsoR1_1 = 0;
        pho_hcalRechitIsoR2_1 = 0;
        pho_hcalRechitIsoR3_1 = 0;
        pho_hcalRechitIsoR4_1 = 0;
        pho_hcalRechitIsoR5_1 = 0;
        pho_trackIsoR1PtCut20_1 = 0;
        pho_trackIsoR2PtCut20_1 = 0;
        pho_trackIsoR3PtCut20_1 = 0;
        pho_trackIsoR4PtCut20_1 = 0;
        pho_trackIsoR5PtCut20_1 = 0;
        pho_swissCrx_1 = 0;
        pho_seedTime_1 = 0;
        matched_eleCharge_1 = 0;
        matched_eleIndex_1 = 0;
        matched_elePt_1 = 0;
        matched_eleEta_1 = 0;
        matched_elePhi_1 = 0;
        matched_eleTrkPt_1 = 0;

        phoE_2 = 0;
        phoEt_2 = 0;
        phoEta_2 = 0;
        phoPhi_2 = 0;
        phoSCE_2 = 0;
        phoSCRawE_2 = 0;
        phoESEn_2 = 0;
        phoSCEta_2 = 0;
        phoSCPhi_2 = 0;
        phoSCEtaWidth_2 = 0;
        phoSCPhiWidth_2 = 0;
        phoSCBrem_2 = 0;
        phohasPixelSeed_2 = 0;
        phoR9_2 = 0;
        phoHoverE_2 = 0;
        phoSigmaIEtaIEta_2 = 0;
        phoE1x3_2 = 0;
        phoE2x2_2 = 0;
        phoE3x3_2 = 0;
        phoE2x5Max_2 = 0;
        phoE1x5_2 = 0;
        phoE2x5_2 = 0;
        phoE5x5_2 = 0;
        phoMaxEnergyXtal_2 = 0;
        phoSigmaEtaEta_2 = 0;
        phoR1x5_2 = 0;
        phoR2x5_2 = 0;
        phoESEffSigmaRR_2 = 0;
        phoSigmaIEtaIEta_2012_2 = 0;
        phoSigmaIEtaIPhi_2012_2 = 0;
        phoSigmaIPhiIPhi_2012_2 = 0;
        phoE1x3_2012_2 = 0;
        phoE2x2_2012_2 = 0;
        phoE3x3_2012_2 = 0;
        phoE2x5Max_2012_2 = 0;
        phoE5x5_2012_2 = 0;
        phoBC1E_2 = 0;
        phoBC1Eta_2 = 0;
        phoBC2E_2 = 0;
        phoBC2Eta_2 = 0;
        pho_ecalClusterIsoR2_2 = 0;
        pho_ecalClusterIsoR3_2 = 0;
        pho_ecalClusterIsoR4_2 = 0;
        pho_ecalClusterIsoR5_2 = 0;
        pho_hcalRechitIsoR1_2 = 0;
        pho_hcalRechitIsoR2_2 = 0;
        pho_hcalRechitIsoR3_2 = 0;
        pho_hcalRechitIsoR4_2 = 0;
        pho_hcalRechitIsoR5_2 = 0;
        pho_trackIsoR1PtCut20_2 = 0;
        pho_trackIsoR2PtCut20_2 = 0;
        pho_trackIsoR3PtCut20_2 = 0;
        pho_trackIsoR4PtCut20_2 = 0;
        pho_trackIsoR5PtCut20_2 = 0;
        pho_swissCrx_2 = 0;
        pho_seedTime_2 = 0;
        matched_eleCharge_2 = 0;
        matched_eleIndex_2 = 0;
        matched_elePt_2 = 0;
        matched_eleEta_2 = 0;
        matched_elePhi_2 = 0;
        matched_eleTrkPt_2 = 0;

        diPhoM = 0;
        diPhoEn = 0;
        diPhoPt = 0;
        diPhoEta = 0;
        diPhoPhi = 0;
    };
    ~diphoton(){};

    float cutDeltaR;
    // Declaration of leaf types
    Int_t           nPho;
    std::vector<float>   *phoE_1;
    std::vector<float>   *phoEt_1;
    std::vector<float>   *phoEta_1;
    std::vector<float>   *phoPhi_1;
    std::vector<float>   *phoSCE_1;
    std::vector<float>   *phoSCRawE_1;
    std::vector<float>   *phoESEn_1;
    std::vector<float>   *phoSCEta_1;
    std::vector<float>   *phoSCPhi_1;
    std::vector<float>   *phoSCEtaWidth_1;
    std::vector<float>   *phoSCPhiWidth_1;
    std::vector<float>   *phoSCBrem_1;
    std::vector<int>     *phohasPixelSeed_1;
    std::vector<float>   *phoR9_1;
    std::vector<float>   *phoHoverE_1;
    std::vector<float>   *phoSigmaIEtaIEta_1;
    std::vector<float>   *phoE1x3_1;
    std::vector<float>   *phoE2x2_1;
    std::vector<float>   *phoE3x3_1;
    std::vector<float>   *phoE2x5Max_1;
    std::vector<float>   *phoE1x5_1;
    std::vector<float>   *phoE2x5_1;
    std::vector<float>   *phoE5x5_1;
    std::vector<float>   *phoMaxEnergyXtal_1;
    std::vector<float>   *phoSigmaEtaEta_1;
    std::vector<float>   *phoR1x5_1;
    std::vector<float>   *phoR2x5_1;
    std::vector<float>   *phoESEffSigmaRR_1;
    std::vector<float>   *phoSigmaIEtaIEta_2012_1;
    std::vector<float>   *phoSigmaIEtaIPhi_2012_1;
    std::vector<float>   *phoSigmaIPhiIPhi_2012_1;
    std::vector<float>   *phoE1x3_2012_1;
    std::vector<float>   *phoE2x2_2012_1;
    std::vector<float>   *phoE3x3_2012_1;
    std::vector<float>   *phoE2x5Max_2012_1;
    std::vector<float>   *phoE5x5_2012_1;
    std::vector<float>   *phoBC1E_1;
    std::vector<float>   *phoBC1Eta_1;
    std::vector<float>   *phoBC2E_1;
    std::vector<float>   *phoBC2Eta_1;
    std::vector<float>   *pho_ecalClusterIsoR2_1;
    std::vector<float>   *pho_ecalClusterIsoR3_1;
    std::vector<float>   *pho_ecalClusterIsoR4_1;
    std::vector<float>   *pho_ecalClusterIsoR5_1;
    std::vector<float>   *pho_hcalRechitIsoR1_1;
    std::vector<float>   *pho_hcalRechitIsoR2_1;
    std::vector<float>   *pho_hcalRechitIsoR3_1;
    std::vector<float>   *pho_hcalRechitIsoR4_1;
    std::vector<float>   *pho_hcalRechitIsoR5_1;
    std::vector<float>   *pho_trackIsoR1PtCut20_1;
    std::vector<float>   *pho_trackIsoR2PtCut20_1;
    std::vector<float>   *pho_trackIsoR3PtCut20_1;
    std::vector<float>   *pho_trackIsoR4PtCut20_1;
    std::vector<float>   *pho_trackIsoR5PtCut20_1;
    std::vector<float>   *pho_swissCrx_1;
    std::vector<float>   *pho_seedTime_1;
    std::vector<int>     *matched_eleCharge_1;
    std::vector<int>     *matched_eleIndex_1;
    std::vector<float>   *matched_elePt_1;
    std::vector<float>   *matched_eleEta_1;
    std::vector<float>   *matched_elePhi_1;
    std::vector<float>   *matched_eleTrkPt_1;

    std::vector<float>   *phoE_2;
    std::vector<float>   *phoEt_2;
    std::vector<float>   *phoEta_2;
    std::vector<float>   *phoPhi_2;
    std::vector<float>   *phoSCE_2;
    std::vector<float>   *phoSCRawE_2;
    std::vector<float>   *phoESEn_2;
    std::vector<float>   *phoSCEta_2;
    std::vector<float>   *phoSCPhi_2;
    std::vector<float>   *phoSCEtaWidth_2;
    std::vector<float>   *phoSCPhiWidth_2;
    std::vector<float>   *phoSCBrem_2;
    std::vector<int>     *phohasPixelSeed_2;
    std::vector<float>   *phoR9_2;
    std::vector<float>   *phoHoverE_2;
    std::vector<float>   *phoSigmaIEtaIEta_2;
    std::vector<float>   *phoE1x3_2;
    std::vector<float>   *phoE2x2_2;
    std::vector<float>   *phoE3x3_2;
    std::vector<float>   *phoE2x5Max_2;
    std::vector<float>   *phoE1x5_2;
    std::vector<float>   *phoE2x5_2;
    std::vector<float>   *phoE5x5_2;
    std::vector<float>   *phoMaxEnergyXtal_2;
    std::vector<float>   *phoSigmaEtaEta_2;
    std::vector<float>   *phoR1x5_2;
    std::vector<float>   *phoR2x5_2;
    std::vector<float>   *phoESEffSigmaRR_2;
    std::vector<float>   *phoSigmaIEtaIEta_2012_2;
    std::vector<float>   *phoSigmaIEtaIPhi_2012_2;
    std::vector<float>   *phoSigmaIPhiIPhi_2012_2;
    std::vector<float>   *phoE1x3_2012_2;
    std::vector<float>   *phoE2x2_2012_2;
    std::vector<float>   *phoE3x3_2012_2;
    std::vector<float>   *phoE2x5Max_2012_2;
    std::vector<float>   *phoE5x5_2012_2;
    std::vector<float>   *phoBC1E_2;
    std::vector<float>   *phoBC1Eta_2;
    std::vector<float>   *phoBC2E_2;
    std::vector<float>   *phoBC2Eta_2;
    std::vector<float>   *pho_ecalClusterIsoR2_2;
    std::vector<float>   *pho_ecalClusterIsoR3_2;
    std::vector<float>   *pho_ecalClusterIsoR4_2;
    std::vector<float>   *pho_ecalClusterIsoR5_2;
    std::vector<float>   *pho_hcalRechitIsoR1_2;
    std::vector<float>   *pho_hcalRechitIsoR2_2;
    std::vector<float>   *pho_hcalRechitIsoR3_2;
    std::vector<float>   *pho_hcalRechitIsoR4_2;
    std::vector<float>   *pho_hcalRechitIsoR5_2;
    std::vector<float>   *pho_trackIsoR1PtCut20_2;
    std::vector<float>   *pho_trackIsoR2PtCut20_2;
    std::vector<float>   *pho_trackIsoR3PtCut20_2;
    std::vector<float>   *pho_trackIsoR4PtCut20_2;
    std::vector<float>   *pho_trackIsoR5PtCut20_2;
    std::vector<float>   *pho_swissCrx_2;
    std::vector<float>   *pho_seedTime_2;
    std::vector<int>     *matched_eleCharge_2;
    std::vector<int>     *matched_eleIndex_2;
    std::vector<float>   *matched_elePt_2;
    std::vector<float>   *matched_eleEta_2;
    std::vector<float>   *matched_elePhi_2;
    std::vector<float>   *matched_eleTrkPt_2;

    std::vector<float>   *diPhoM;
    std::vector<float>   *diPhoEn;
    std::vector<float>   *diPhoPt;
    std::vector<float>   *diPhoEta;
    std::vector<float>   *diPhoPhi;

    // List of branches
    TBranch        *b_nPho;
    TBranch        *b_phoE_1;
    TBranch        *b_phoEt_1;
    TBranch        *b_phoEta_1;
    TBranch        *b_phoPhi_1;
    TBranch        *b_phoSCE_1;
    TBranch        *b_phoSCRawE_1;
    TBranch        *b_phoESEn_1;
    TBranch        *b_phoSCEta_1;
    TBranch        *b_phoSCPhi_1;
    TBranch        *b_phoSCEtaWidth_1;
    TBranch        *b_phoSCPhiWidth_1;
    TBranch        *b_phoSCBrem_1;
    TBranch        *b_phohasPixelSeed_1;
    TBranch        *b_phoR9_1;
    TBranch        *b_phoHoverE_1;
    TBranch        *b_phoSigmaIEtaIEta_1;
    TBranch        *b_phoE1x3_1;
    TBranch        *b_phoE2x2_1;
    TBranch        *b_phoE3x3_1;
    TBranch        *b_phoE2x5Max_1;
    TBranch        *b_phoE1x5_1;
    TBranch        *b_phoE2x5_1;
    TBranch        *b_phoE5x5_1;
    TBranch        *b_phoMaxEnergyXtal_1;
    TBranch        *b_phoSigmaEtaEta_1;
    TBranch        *b_phoR1x5_1;
    TBranch        *b_phoR2x5_1;
    TBranch        *b_phoESEffSigmaRR_1;
    TBranch        *b_phoSigmaIEtaIEta_2012_1;
    TBranch        *b_phoSigmaIEtaIPhi_2012_1;
    TBranch        *b_phoSigmaIPhiIPhi_2012_1;
    TBranch        *b_phoE1x3_2012_1;
    TBranch        *b_phoE2x2_2012_1;
    TBranch        *b_phoE3x3_2012_1;
    TBranch        *b_phoE2x5Max_2012_1;
    TBranch        *b_phoE5x5_2012_1;
    TBranch        *b_phoBC1E_1;
    TBranch        *b_phoBC1Eta_1;
    TBranch        *b_phoBC2E_1;
    TBranch        *b_phoBC2Eta_1;
    TBranch        *b_pho_ecalClusterIsoR2_1;
    TBranch        *b_pho_ecalClusterIsoR3_1;
    TBranch        *b_pho_ecalClusterIsoR4_1;
    TBranch        *b_pho_ecalClusterIsoR5_1;
    TBranch        *b_pho_hcalRechitIsoR1_1;
    TBranch        *b_pho_hcalRechitIsoR2_1;
    TBranch        *b_pho_hcalRechitIsoR3_1;
    TBranch        *b_pho_hcalRechitIsoR4_1;
    TBranch        *b_pho_hcalRechitIsoR5_1;
    TBranch        *b_pho_trackIsoR1PtCut20_1;
    TBranch        *b_pho_trackIsoR2PtCut20_1;
    TBranch        *b_pho_trackIsoR3PtCut20_1;
    TBranch        *b_pho_trackIsoR4PtCut20_1;
    TBranch        *b_pho_trackIsoR5PtCut20_1;
    TBranch        *b_pho_swissCrx_1;
    TBranch        *b_pho_seedTime_1;
    TBranch        *b_matched_eleCharge_1;
    TBranch        *b_matched_eleIndex_1;
    TBranch        *b_matched_elePt_1;
    TBranch        *b_matched_eleEta_1;
    TBranch        *b_matched_elePhi_1;
    TBranch        *b_matched_eleTrkPt_1;

    TBranch        *b_phoE_2;
    TBranch        *b_phoEt_2;
    TBranch        *b_phoEta_2;
    TBranch        *b_phoPhi_2;
    TBranch        *b_phoSCE_2;
    TBranch        *b_phoSCRawE_2;
    TBranch        *b_phoESEn_2;
    TBranch        *b_phoSCEta_2;
    TBranch        *b_phoSCPhi_2;
    TBranch        *b_phoSCEtaWidth_2;
    TBranch        *b_phoSCPhiWidth_2;
    TBranch        *b_phoSCBrem_2;
    TBranch        *b_phohasPixelSeed_2;
    TBranch        *b_phoR9_2;
    TBranch        *b_phoHoverE_2;
    TBranch        *b_phoSigmaIEtaIEta_2;
    TBranch        *b_phoE1x3_2;
    TBranch        *b_phoE2x2_2;
    TBranch        *b_phoE3x3_2;
    TBranch        *b_phoE2x5Max_2;
    TBranch        *b_phoE1x5_2;
    TBranch        *b_phoE2x5_2;
    TBranch        *b_phoE5x5_2;
    TBranch        *b_phoMaxEnergyXtal_2;
    TBranch        *b_phoSigmaEtaEta_2;
    TBranch        *b_phoR1x5_2;
    TBranch        *b_phoR2x5_2;
    TBranch        *b_phoESEffSigmaRR_2;
    TBranch        *b_phoSigmaIEtaIEta_2012_2;
    TBranch        *b_phoSigmaIEtaIPhi_2012_2;
    TBranch        *b_phoSigmaIPhiIPhi_2012_2;
    TBranch        *b_phoE1x3_2012_2;
    TBranch        *b_phoE2x2_2012_2;
    TBranch        *b_phoE3x3_2012_2;
    TBranch        *b_phoE2x5Max_2012_2;
    TBranch        *b_phoE5x5_2012_2;
    TBranch        *b_phoBC1E_2;
    TBranch        *b_phoBC1Eta_2;
    TBranch        *b_phoBC2E_2;
    TBranch        *b_phoBC2Eta_2;
    TBranch        *b_pho_ecalClusterIsoR2_2;
    TBranch        *b_pho_ecalClusterIsoR3_2;
    TBranch        *b_pho_ecalClusterIsoR4_2;
    TBranch        *b_pho_ecalClusterIsoR5_2;
    TBranch        *b_pho_hcalRechitIsoR1_2;
    TBranch        *b_pho_hcalRechitIsoR2_2;
    TBranch        *b_pho_hcalRechitIsoR3_2;
    TBranch        *b_pho_hcalRechitIsoR4_2;
    TBranch        *b_pho_hcalRechitIsoR5_2;
    TBranch        *b_pho_trackIsoR1PtCut20_2;
    TBranch        *b_pho_trackIsoR2PtCut20_2;
    TBranch        *b_pho_trackIsoR3PtCut20_2;
    TBranch        *b_pho_trackIsoR4PtCut20_2;
    TBranch        *b_pho_trackIsoR5PtCut20_2;
    TBranch        *b_pho_swissCrx_2;
    TBranch        *b_pho_seedTime_2;
    TBranch        *b_matched_eleCharge_2;
    TBranch        *b_matched_eleIndex_2;
    TBranch        *b_matched_elePt_2;
    TBranch        *b_matched_eleEta_2;
    TBranch        *b_matched_elePhi_2;
    TBranch        *b_matched_eleTrkPt_2;

    TBranch        *b_diPhoM;
    TBranch        *b_diPhoEn;
    TBranch        *b_diPhoPt;
    TBranch        *b_diPhoEta;
    TBranch        *b_diPhoPhi;

    // list of objects to be used when creating a diPhoton Tree
    Int_t           nPho_out;
    std::vector<float>   phoE_1_out;
    std::vector<float>   phoEt_1_out;
    std::vector<float>   phoEta_1_out;
    std::vector<float>   phoPhi_1_out;
    std::vector<float>   phoSCE_1_out;
    std::vector<float>   phoSCRawE_1_out;
    std::vector<float>   phoESEn_1_out;
    std::vector<float>   phoSCEta_1_out;
    std::vector<float>   phoSCPhi_1_out;
    std::vector<float>   phoSCEtaWidth_1_out;
    std::vector<float>   phoSCPhiWidth_1_out;
    std::vector<float>   phoSCBrem_1_out;
    std::vector<int>     phohasPixelSeed_1_out;
    std::vector<float>   phoR9_1_out;
    std::vector<float>   phoHoverE_1_out;
    std::vector<float>   phoSigmaIEtaIEta_1_out;
    std::vector<float>   phoE1x3_1_out;
    std::vector<float>   phoE2x2_1_out;
    std::vector<float>   phoE3x3_1_out;
    std::vector<float>   phoE2x5Max_1_out;
    std::vector<float>   phoE1x5_1_out;
    std::vector<float>   phoE2x5_1_out;
    std::vector<float>   phoE5x5_1_out;
    std::vector<float>   phoMaxEnergyXtal_1_out;
    std::vector<float>   phoSigmaEtaEta_1_out;
    std::vector<float>   phoR1x5_1_out;
    std::vector<float>   phoR2x5_1_out;
    std::vector<float>   phoESEffSigmaRR_1_out;
    std::vector<float>   phoSigmaIEtaIEta_2012_1_out;
    std::vector<float>   phoSigmaIEtaIPhi_2012_1_out;
    std::vector<float>   phoSigmaIPhiIPhi_2012_1_out;
    std::vector<float>   phoE1x3_2012_1_out;
    std::vector<float>   phoE2x2_2012_1_out;
    std::vector<float>   phoE3x3_2012_1_out;
    std::vector<float>   phoE2x5Max_2012_1_out;
    std::vector<float>   phoE5x5_2012_1_out;
    std::vector<float>   phoBC1E_1_out;
    std::vector<float>   phoBC1Eta_1_out;
    std::vector<float>   phoBC2E_1_out;
    std::vector<float>   phoBC2Eta_1_out;
    std::vector<float>   pho_ecalClusterIsoR2_1_out;
    std::vector<float>   pho_ecalClusterIsoR3_1_out;
    std::vector<float>   pho_ecalClusterIsoR4_1_out;
    std::vector<float>   pho_ecalClusterIsoR5_1_out;
    std::vector<float>   pho_hcalRechitIsoR1_1_out;
    std::vector<float>   pho_hcalRechitIsoR2_1_out;
    std::vector<float>   pho_hcalRechitIsoR3_1_out;
    std::vector<float>   pho_hcalRechitIsoR4_1_out;
    std::vector<float>   pho_hcalRechitIsoR5_1_out;
    std::vector<float>   pho_trackIsoR1PtCut20_1_out;
    std::vector<float>   pho_trackIsoR2PtCut20_1_out;
    std::vector<float>   pho_trackIsoR3PtCut20_1_out;
    std::vector<float>   pho_trackIsoR4PtCut20_1_out;
    std::vector<float>   pho_trackIsoR5PtCut20_1_out;
    std::vector<float>   pho_swissCrx_1_out;
    std::vector<float>   pho_seedTime_1_out;
    std::vector<int>     matched_eleCharge_1_out;
    std::vector<int>     matched_eleIndex_1_out;
    std::vector<float>   matched_elePt_1_out;
    std::vector<float>   matched_eleEta_1_out;
    std::vector<float>   matched_elePhi_1_out;
    std::vector<float>   matched_eleTrkPt_1_out;

    std::vector<float>   phoE_2_out;
    std::vector<float>   phoEt_2_out;
    std::vector<float>   phoEta_2_out;
    std::vector<float>   phoPhi_2_out;
    std::vector<float>   phoSCE_2_out;
    std::vector<float>   phoSCRawE_2_out;
    std::vector<float>   phoESEn_2_out;
    std::vector<float>   phoSCEta_2_out;
    std::vector<float>   phoSCPhi_2_out;
    std::vector<float>   phoSCEtaWidth_2_out;
    std::vector<float>   phoSCPhiWidth_2_out;
    std::vector<float>   phoSCBrem_2_out;
    std::vector<int>     phohasPixelSeed_2_out;
    std::vector<float>   phoR9_2_out;
    std::vector<float>   phoHoverE_2_out;
    std::vector<float>   phoSigmaIEtaIEta_2_out;
    std::vector<float>   phoE1x3_2_out;
    std::vector<float>   phoE2x2_2_out;
    std::vector<float>   phoE3x3_2_out;
    std::vector<float>   phoE2x5Max_2_out;
    std::vector<float>   phoE1x5_2_out;
    std::vector<float>   phoE2x5_2_out;
    std::vector<float>   phoE5x5_2_out;
    std::vector<float>   phoMaxEnergyXtal_2_out;
    std::vector<float>   phoSigmaEtaEta_2_out;
    std::vector<float>   phoR1x5_2_out;
    std::vector<float>   phoR2x5_2_out;
    std::vector<float>   phoESEffSigmaRR_2_out;
    std::vector<float>   phoSigmaIEtaIEta_2012_2_out;
    std::vector<float>   phoSigmaIEtaIPhi_2012_2_out;
    std::vector<float>   phoSigmaIPhiIPhi_2012_2_out;
    std::vector<float>   phoE1x3_2012_2_out;
    std::vector<float>   phoE2x2_2012_2_out;
    std::vector<float>   phoE3x3_2012_2_out;
    std::vector<float>   phoE2x5Max_2012_2_out;
    std::vector<float>   phoE5x5_2012_2_out;
    std::vector<float>   phoBC1E_2_out;
    std::vector<float>   phoBC1Eta_2_out;
    std::vector<float>   phoBC2E_2_out;
    std::vector<float>   phoBC2Eta_2_out;
    std::vector<float>   pho_ecalClusterIsoR2_2_out;
    std::vector<float>   pho_ecalClusterIsoR3_2_out;
    std::vector<float>   pho_ecalClusterIsoR4_2_out;
    std::vector<float>   pho_ecalClusterIsoR5_2_out;
    std::vector<float>   pho_hcalRechitIsoR1_2_out;
    std::vector<float>   pho_hcalRechitIsoR2_2_out;
    std::vector<float>   pho_hcalRechitIsoR3_2_out;
    std::vector<float>   pho_hcalRechitIsoR4_2_out;
    std::vector<float>   pho_hcalRechitIsoR5_2_out;
    std::vector<float>   pho_trackIsoR1PtCut20_2_out;
    std::vector<float>   pho_trackIsoR2PtCut20_2_out;
    std::vector<float>   pho_trackIsoR3PtCut20_2_out;
    std::vector<float>   pho_trackIsoR4PtCut20_2_out;
    std::vector<float>   pho_trackIsoR5PtCut20_2_out;
    std::vector<float>   pho_swissCrx_2_out;
    std::vector<float>   pho_seedTime_2_out;
    std::vector<int>     matched_eleCharge_2_out;
    std::vector<int>     matched_eleIndex_2_out;
    std::vector<float>   matched_elePt_2_out;
    std::vector<float>   matched_eleEta_2_out;
    std::vector<float>   matched_elePhi_2_out;
    std::vector<float>   matched_eleTrkPt_2_out;

    std::vector<float>   diPhoM_out;
    std::vector<float>   diPhoEn_out;
    std::vector<float>   diPhoPt_out;
    std::vector<float>   diPhoEta_out;
    std::vector<float>   diPhoPhi_out;
};

void setupDiPhotonTree(TTree *t,diphoton &tdiphoton);
void branchDiPhotonTree(TTree *t,diphoton &tdiphoton);
void makeDiPhotonPairs(ggHiNtuplizer &tggHiNtuplizer, diphoton &tdiphoton, bool doEleMatch = true, bool doSizeCheck = true);
Double_t getDR  ( Double_t eta1, Double_t phi1, Double_t eta2, Double_t phi2);
Double_t getDPHI( Double_t phi1, Double_t phi2);

void setupDiPhotonTree(TTree *t,diphoton &tdiphoton)
{
    // Set branch addresses and branch pointers
    if (t->GetBranch("nPho"))  t->SetBranchAddress("nPho", &tdiphoton.nPho, &tdiphoton.b_nPho);

    if (t->GetBranch("phoE_1"))  t->SetBranchAddress("phoE_1", &tdiphoton.phoE_1, &tdiphoton.b_phoE_1);
    if (t->GetBranch("phoEt_1"))  t->SetBranchAddress("phoEt_1", &tdiphoton.phoEt_1, &tdiphoton.b_phoEt_1);
    if (t->GetBranch("phoEta_1"))  t->SetBranchAddress("phoEta_1", &tdiphoton.phoEta_1, &tdiphoton.b_phoEta_1);
    if (t->GetBranch("phoPhi_1"))  t->SetBranchAddress("phoPhi_1", &tdiphoton.phoPhi_1, &tdiphoton.b_phoPhi_1);
    if (t->GetBranch("phoSCE_1"))  t->SetBranchAddress("phoSCE_1", &tdiphoton.phoSCE_1, &tdiphoton.b_phoSCE_1);
    if (t->GetBranch("phoSCRawE_1"))  t->SetBranchAddress("phoSCRawE_1", &tdiphoton.phoSCRawE_1, &tdiphoton.b_phoSCRawE_1);
    if (t->GetBranch("phoESEn_1"))  t->SetBranchAddress("phoESEn_1", &tdiphoton.phoESEn_1, &tdiphoton.b_phoESEn_1);
    if (t->GetBranch("phoSCEta_1"))  t->SetBranchAddress("phoSCEta_1", &tdiphoton.phoSCEta_1, &tdiphoton.b_phoSCEta_1);
    if (t->GetBranch("phoSCPhi_1"))  t->SetBranchAddress("phoSCPhi_1", &tdiphoton.phoSCPhi_1, &tdiphoton.b_phoSCPhi_1);
    if (t->GetBranch("phoSCEtaWidth_1"))  t->SetBranchAddress("phoSCEtaWidth_1", &tdiphoton.phoSCEtaWidth_1, &tdiphoton.b_phoSCEtaWidth_1);
    if (t->GetBranch("phoSCPhiWidth_1"))  t->SetBranchAddress("phoSCPhiWidth_1", &tdiphoton.phoSCPhiWidth_1, &tdiphoton.b_phoSCPhiWidth_1);
    if (t->GetBranch("phoSCBrem_1"))  t->SetBranchAddress("phoSCBrem_1", &tdiphoton.phoSCBrem_1, &tdiphoton.b_phoSCBrem_1);
    if (t->GetBranch("phohasPixelSeed_1"))  t->SetBranchAddress("phohasPixelSeed_1", &tdiphoton.phohasPixelSeed_1, &tdiphoton.b_phohasPixelSeed_1);
    if (t->GetBranch("phoR9_1"))  t->SetBranchAddress("phoR9_1", &tdiphoton.phoR9_1, &tdiphoton.b_phoR9_1);
    if (t->GetBranch("phoHoverE_1"))  t->SetBranchAddress("phoHoverE_1", &tdiphoton.phoHoverE_1, &tdiphoton.b_phoHoverE_1);
    if (t->GetBranch("phoSigmaIEtaIEta_1"))  t->SetBranchAddress("phoSigmaIEtaIEta_1", &tdiphoton.phoSigmaIEtaIEta_1, &tdiphoton.b_phoSigmaIEtaIEta_1);
    if (t->GetBranch("phoE1x3_1"))  t->SetBranchAddress("phoE1x3_1", &tdiphoton.phoE1x3_1, &tdiphoton.b_phoE1x3_1);
    if (t->GetBranch("phoE2x2_1"))  t->SetBranchAddress("phoE2x2_1", &tdiphoton.phoE2x2_1, &tdiphoton.b_phoE2x2_1);
    if (t->GetBranch("phoE3x3_1"))  t->SetBranchAddress("phoE3x3_1", &tdiphoton.phoE3x3_1, &tdiphoton.b_phoE3x3_1);
    if (t->GetBranch("phoE2x5Max_1"))  t->SetBranchAddress("phoE2x5Max_1", &tdiphoton.phoE2x5Max_1, &tdiphoton.b_phoE2x5Max_1);
    if (t->GetBranch("phoE1x5_1"))  t->SetBranchAddress("phoE1x5_1", &tdiphoton.phoE1x5_1, &tdiphoton.b_phoE1x5_1);
    if (t->GetBranch("phoE2x5_1"))  t->SetBranchAddress("phoE2x5_1", &tdiphoton.phoE2x5_1, &tdiphoton.b_phoE2x5_1);
    if (t->GetBranch("phoE5x5_1"))  t->SetBranchAddress("phoE5x5_1", &tdiphoton.phoE5x5_1, &tdiphoton.b_phoE5x5_1);
    if (t->GetBranch("phoMaxEnergyXtal_1"))  t->SetBranchAddress("phoMaxEnergyXtal_1", &tdiphoton.phoMaxEnergyXtal_1, &tdiphoton.b_phoMaxEnergyXtal_1);
    if (t->GetBranch("phoSigmaEtaEta_1"))  t->SetBranchAddress("phoSigmaEtaEta_1", &tdiphoton.phoSigmaEtaEta_1, &tdiphoton.b_phoSigmaEtaEta_1);
    if (t->GetBranch("phoR1x5_1"))  t->SetBranchAddress("phoR1x5_1", &tdiphoton.phoR1x5_1, &tdiphoton.b_phoR1x5_1);
    if (t->GetBranch("phoR2x5_1"))  t->SetBranchAddress("phoR2x5_1", &tdiphoton.phoR2x5_1, &tdiphoton.b_phoR2x5_1);
    if (t->GetBranch("phoESEffSigmaRR_1"))  t->SetBranchAddress("phoESEffSigmaRR_1", &tdiphoton.phoESEffSigmaRR_1, &tdiphoton.b_phoESEffSigmaRR_1);
    if (t->GetBranch("phoSigmaIEtaIEta_2012_1"))  t->SetBranchAddress("phoSigmaIEtaIEta_2012_1", &tdiphoton.phoSigmaIEtaIEta_2012_1, &tdiphoton.b_phoSigmaIEtaIEta_2012_1);
    if (t->GetBranch("phoSigmaIEtaIPhi_2012_1"))  t->SetBranchAddress("phoSigmaIEtaIPhi_2012_1", &tdiphoton.phoSigmaIEtaIPhi_2012_1, &tdiphoton.b_phoSigmaIEtaIPhi_2012_1);
    if (t->GetBranch("phoSigmaIPhiIPhi_2012_1"))  t->SetBranchAddress("phoSigmaIPhiIPhi_2012_1", &tdiphoton.phoSigmaIPhiIPhi_2012_1, &tdiphoton.b_phoSigmaIPhiIPhi_2012_1);
    if (t->GetBranch("phoE1x3_2012_1"))  t->SetBranchAddress("phoE1x3_2012_1", &tdiphoton.phoE1x3_2012_1, &tdiphoton.b_phoE1x3_2012_1);
    if (t->GetBranch("phoE2x2_2012_1"))  t->SetBranchAddress("phoE2x2_2012_1", &tdiphoton.phoE2x2_2012_1, &tdiphoton.b_phoE2x2_2012_1);
    if (t->GetBranch("phoE3x3_2012_1"))  t->SetBranchAddress("phoE3x3_2012_1", &tdiphoton.phoE3x3_2012_1, &tdiphoton.b_phoE3x3_2012_1);
    if (t->GetBranch("phoE2x5Max_2012_1"))  t->SetBranchAddress("phoE2x5Max_2012_1", &tdiphoton.phoE2x5Max_2012_1, &tdiphoton.b_phoE2x5Max_2012_1);
    if (t->GetBranch("phoE5x5_2012_1"))  t->SetBranchAddress("phoE5x5_2012_1", &tdiphoton.phoE5x5_2012_1, &tdiphoton.b_phoE5x5_2012_1);
    if (t->GetBranch("phoBC1E_1"))  t->SetBranchAddress("phoBC1E_1", &tdiphoton.phoBC1E_1, &tdiphoton.b_phoBC1E_1);
    if (t->GetBranch("phoBC1Eta_1"))  t->SetBranchAddress("phoBC1Eta_1", &tdiphoton.phoBC1Eta_1, &tdiphoton.b_phoBC1Eta_1);
    if (t->GetBranch("phoBC2E_1"))  t->SetBranchAddress("phoBC2E_1", &tdiphoton.phoBC2E_1, &tdiphoton.b_phoBC2E_1);
    if (t->GetBranch("phoBC2Eta_1"))  t->SetBranchAddress("phoBC2Eta_1", &tdiphoton.phoBC2Eta_1, &tdiphoton.b_phoBC2Eta_1);
    if (t->GetBranch("pho_ecalClusterIsoR2_1"))  t->SetBranchAddress("pho_ecalClusterIsoR2_1", &tdiphoton.pho_ecalClusterIsoR2_1, &tdiphoton.b_pho_ecalClusterIsoR2_1);
    if (t->GetBranch("pho_ecalClusterIsoR3_1"))  t->SetBranchAddress("pho_ecalClusterIsoR3_1", &tdiphoton.pho_ecalClusterIsoR3_1, &tdiphoton.b_pho_ecalClusterIsoR3_1);
    if (t->GetBranch("pho_ecalClusterIsoR4_1"))  t->SetBranchAddress("pho_ecalClusterIsoR4_1", &tdiphoton.pho_ecalClusterIsoR4_1, &tdiphoton.b_pho_ecalClusterIsoR4_1);
    if (t->GetBranch("pho_ecalClusterIsoR5_1"))  t->SetBranchAddress("pho_ecalClusterIsoR5_1", &tdiphoton.pho_ecalClusterIsoR5_1, &tdiphoton.b_pho_ecalClusterIsoR5_1);
    if (t->GetBranch("pho_hcalRechitIsoR1_1"))  t->SetBranchAddress("pho_hcalRechitIsoR1_1", &tdiphoton.pho_hcalRechitIsoR1_1, &tdiphoton.b_pho_hcalRechitIsoR1_1);
    if (t->GetBranch("pho_hcalRechitIsoR2_1"))  t->SetBranchAddress("pho_hcalRechitIsoR2_1", &tdiphoton.pho_hcalRechitIsoR2_1, &tdiphoton.b_pho_hcalRechitIsoR2_1);
    if (t->GetBranch("pho_hcalRechitIsoR3_1"))  t->SetBranchAddress("pho_hcalRechitIsoR3_1", &tdiphoton.pho_hcalRechitIsoR3_1, &tdiphoton.b_pho_hcalRechitIsoR3_1);
    if (t->GetBranch("pho_hcalRechitIsoR4_1"))  t->SetBranchAddress("pho_hcalRechitIsoR4_1", &tdiphoton.pho_hcalRechitIsoR4_1, &tdiphoton.b_pho_hcalRechitIsoR4_1);
    if (t->GetBranch("pho_hcalRechitIsoR5_1"))  t->SetBranchAddress("pho_hcalRechitIsoR5_1", &tdiphoton.pho_hcalRechitIsoR5_1, &tdiphoton.b_pho_hcalRechitIsoR5_1);
    if (t->GetBranch("pho_trackIsoR1PtCut20_1"))  t->SetBranchAddress("pho_trackIsoR1PtCut20_1", &tdiphoton.pho_trackIsoR1PtCut20_1, &tdiphoton.b_pho_trackIsoR1PtCut20_1);
    if (t->GetBranch("pho_trackIsoR2PtCut20_1"))  t->SetBranchAddress("pho_trackIsoR2PtCut20_1", &tdiphoton.pho_trackIsoR2PtCut20_1, &tdiphoton.b_pho_trackIsoR2PtCut20_1);
    if (t->GetBranch("pho_trackIsoR3PtCut20_1"))  t->SetBranchAddress("pho_trackIsoR3PtCut20_1", &tdiphoton.pho_trackIsoR3PtCut20_1, &tdiphoton.b_pho_trackIsoR3PtCut20_1);
    if (t->GetBranch("pho_trackIsoR4PtCut20_1"))  t->SetBranchAddress("pho_trackIsoR4PtCut20_1", &tdiphoton.pho_trackIsoR4PtCut20_1, &tdiphoton.b_pho_trackIsoR4PtCut20_1);
    if (t->GetBranch("pho_trackIsoR5PtCut20_1"))  t->SetBranchAddress("pho_trackIsoR5PtCut20_1", &tdiphoton.pho_trackIsoR5PtCut20_1, &tdiphoton.b_pho_trackIsoR5PtCut20_1);
    if (t->GetBranch("pho_swissCrx_1"))  t->SetBranchAddress("pho_swissCrx_1", &tdiphoton.pho_swissCrx_1, &tdiphoton.b_pho_swissCrx_1);
    if (t->GetBranch("pho_seedTime_1"))  t->SetBranchAddress("pho_seedTime_1", &tdiphoton.pho_seedTime_1, &tdiphoton.b_pho_seedTime_1);
    if (t->GetBranch("matched_eleCharge_1"))  t->SetBranchAddress("matched_eleCharge_1", &tdiphoton.matched_eleCharge_1, &tdiphoton.b_matched_eleCharge_1);
    if (t->GetBranch("matched_eleIndex_1"))  t->SetBranchAddress("matched_eleIndex_1", &tdiphoton.matched_eleIndex_1, &tdiphoton.b_matched_eleIndex_1);
    if (t->GetBranch("matched_elePt_1"))  t->SetBranchAddress("matched_elePt_1", &tdiphoton.matched_elePt_1, &tdiphoton.b_matched_elePt_1);
    if (t->GetBranch("matched_eleEta_1"))  t->SetBranchAddress("matched_eleEta_1", &tdiphoton.matched_eleEta_1, &tdiphoton.b_matched_eleEta_1);
    if (t->GetBranch("matched_elePhi_1"))  t->SetBranchAddress("matched_elePhi_1", &tdiphoton.matched_elePhi_1, &tdiphoton.b_matched_elePhi_1);
    if (t->GetBranch("matched_eleTrkPt_1"))  t->SetBranchAddress("matched_eleTrkPt_1", &tdiphoton.matched_eleTrkPt_1, &tdiphoton.b_matched_eleTrkPt_1);

    if (t->GetBranch("phoE_2"))  t->SetBranchAddress("phoE_2", &tdiphoton.phoE_2, &tdiphoton.b_phoE_2);
    if (t->GetBranch("phoEt_2"))  t->SetBranchAddress("phoEt_2", &tdiphoton.phoEt_2, &tdiphoton.b_phoEt_2);
    if (t->GetBranch("phoEta_2"))  t->SetBranchAddress("phoEta_2", &tdiphoton.phoEta_2, &tdiphoton.b_phoEta_2);
    if (t->GetBranch("phoPhi_2"))  t->SetBranchAddress("phoPhi_2", &tdiphoton.phoPhi_2, &tdiphoton.b_phoPhi_2);
    if (t->GetBranch("phoSCE_2"))  t->SetBranchAddress("phoSCE_2", &tdiphoton.phoSCE_2, &tdiphoton.b_phoSCE_2);
    if (t->GetBranch("phoSCRawE_2"))  t->SetBranchAddress("phoSCRawE_2", &tdiphoton.phoSCRawE_2, &tdiphoton.b_phoSCRawE_2);
    if (t->GetBranch("phoESEn_2"))  t->SetBranchAddress("phoESEn_2", &tdiphoton.phoESEn_2, &tdiphoton.b_phoESEn_2);
    if (t->GetBranch("phoSCEta_2"))  t->SetBranchAddress("phoSCEta_2", &tdiphoton.phoSCEta_2, &tdiphoton.b_phoSCEta_2);
    if (t->GetBranch("phoSCPhi_2"))  t->SetBranchAddress("phoSCPhi_2", &tdiphoton.phoSCPhi_2, &tdiphoton.b_phoSCPhi_2);
    if (t->GetBranch("phoSCEtaWidth_2"))  t->SetBranchAddress("phoSCEtaWidth_2", &tdiphoton.phoSCEtaWidth_2, &tdiphoton.b_phoSCEtaWidth_2);
    if (t->GetBranch("phoSCPhiWidth_2"))  t->SetBranchAddress("phoSCPhiWidth_2", &tdiphoton.phoSCPhiWidth_2, &tdiphoton.b_phoSCPhiWidth_2);
    if (t->GetBranch("phoSCBrem_2"))  t->SetBranchAddress("phoSCBrem_2", &tdiphoton.phoSCBrem_2, &tdiphoton.b_phoSCBrem_2);
    if (t->GetBranch("phohasPixelSeed_2"))  t->SetBranchAddress("phohasPixelSeed_2", &tdiphoton.phohasPixelSeed_2, &tdiphoton.b_phohasPixelSeed_2);
    if (t->GetBranch("phoR9_2"))  t->SetBranchAddress("phoR9_2", &tdiphoton.phoR9_2, &tdiphoton.b_phoR9_2);
    if (t->GetBranch("phoHoverE_2"))  t->SetBranchAddress("phoHoverE_2", &tdiphoton.phoHoverE_2, &tdiphoton.b_phoHoverE_2);
    if (t->GetBranch("phoSigmaIEtaIEta_2"))  t->SetBranchAddress("phoSigmaIEtaIEta_2", &tdiphoton.phoSigmaIEtaIEta_2, &tdiphoton.b_phoSigmaIEtaIEta_2);
    if (t->GetBranch("phoE1x3_2"))  t->SetBranchAddress("phoE1x3_2", &tdiphoton.phoE1x3_2, &tdiphoton.b_phoE1x3_2);
    if (t->GetBranch("phoE2x2_2"))  t->SetBranchAddress("phoE2x2_2", &tdiphoton.phoE2x2_2, &tdiphoton.b_phoE2x2_2);
    if (t->GetBranch("phoE3x3_2"))  t->SetBranchAddress("phoE3x3_2", &tdiphoton.phoE3x3_2, &tdiphoton.b_phoE3x3_2);
    if (t->GetBranch("phoE2x5Max_2"))  t->SetBranchAddress("phoE2x5Max_2", &tdiphoton.phoE2x5Max_2, &tdiphoton.b_phoE2x5Max_2);
    if (t->GetBranch("phoE1x5_2"))  t->SetBranchAddress("phoE1x5_2", &tdiphoton.phoE1x5_2, &tdiphoton.b_phoE1x5_2);
    if (t->GetBranch("phoE2x5_2"))  t->SetBranchAddress("phoE2x5_2", &tdiphoton.phoE2x5_2, &tdiphoton.b_phoE2x5_2);
    if (t->GetBranch("phoE5x5_2"))  t->SetBranchAddress("phoE5x5_2", &tdiphoton.phoE5x5_2, &tdiphoton.b_phoE5x5_2);
    if (t->GetBranch("phoMaxEnergyXtal_2"))  t->SetBranchAddress("phoMaxEnergyXtal_2", &tdiphoton.phoMaxEnergyXtal_2, &tdiphoton.b_phoMaxEnergyXtal_2);
    if (t->GetBranch("phoSigmaEtaEta_2"))  t->SetBranchAddress("phoSigmaEtaEta_2", &tdiphoton.phoSigmaEtaEta_2, &tdiphoton.b_phoSigmaEtaEta_2);
    if (t->GetBranch("phoR1x5_2"))  t->SetBranchAddress("phoR1x5_2", &tdiphoton.phoR1x5_2, &tdiphoton.b_phoR1x5_2);
    if (t->GetBranch("phoR2x5_2"))  t->SetBranchAddress("phoR2x5_2", &tdiphoton.phoR2x5_2, &tdiphoton.b_phoR2x5_2);
    if (t->GetBranch("phoESEffSigmaRR_2"))  t->SetBranchAddress("phoESEffSigmaRR_2", &tdiphoton.phoESEffSigmaRR_2, &tdiphoton.b_phoESEffSigmaRR_2);
    if (t->GetBranch("phoSigmaIEtaIEta_2012_2"))  t->SetBranchAddress("phoSigmaIEtaIEta_2012_2", &tdiphoton.phoSigmaIEtaIEta_2012_2, &tdiphoton.b_phoSigmaIEtaIEta_2012_2);
    if (t->GetBranch("phoSigmaIEtaIPhi_2012_2"))  t->SetBranchAddress("phoSigmaIEtaIPhi_2012_2", &tdiphoton.phoSigmaIEtaIPhi_2012_2, &tdiphoton.b_phoSigmaIEtaIPhi_2012_2);
    if (t->GetBranch("phoSigmaIPhiIPhi_2012_2"))  t->SetBranchAddress("phoSigmaIPhiIPhi_2012_2", &tdiphoton.phoSigmaIPhiIPhi_2012_2, &tdiphoton.b_phoSigmaIPhiIPhi_2012_2);
    if (t->GetBranch("phoE1x3_2012_2"))  t->SetBranchAddress("phoE1x3_2012_2", &tdiphoton.phoE1x3_2012_2, &tdiphoton.b_phoE1x3_2012_2);
    if (t->GetBranch("phoE2x2_2012_2"))  t->SetBranchAddress("phoE2x2_2012_2", &tdiphoton.phoE2x2_2012_2, &tdiphoton.b_phoE2x2_2012_2);
    if (t->GetBranch("phoE3x3_2012_2"))  t->SetBranchAddress("phoE3x3_2012_2", &tdiphoton.phoE3x3_2012_2, &tdiphoton.b_phoE3x3_2012_2);
    if (t->GetBranch("phoE2x5Max_2012_2"))  t->SetBranchAddress("phoE2x5Max_2012_2", &tdiphoton.phoE2x5Max_2012_2, &tdiphoton.b_phoE2x5Max_2012_2);
    if (t->GetBranch("phoE5x5_2012_2"))  t->SetBranchAddress("phoE5x5_2012_2", &tdiphoton.phoE5x5_2012_2, &tdiphoton.b_phoE5x5_2012_2);
    if (t->GetBranch("phoBC1E_2"))  t->SetBranchAddress("phoBC1E_2", &tdiphoton.phoBC1E_2, &tdiphoton.b_phoBC1E_2);
    if (t->GetBranch("phoBC1Eta_2"))  t->SetBranchAddress("phoBC1Eta_2", &tdiphoton.phoBC1Eta_2, &tdiphoton.b_phoBC1Eta_2);
    if (t->GetBranch("phoBC2E_2"))  t->SetBranchAddress("phoBC2E_2", &tdiphoton.phoBC2E_2, &tdiphoton.b_phoBC2E_2);
    if (t->GetBranch("phoBC2Eta_2"))  t->SetBranchAddress("phoBC2Eta_2", &tdiphoton.phoBC2Eta_2, &tdiphoton.b_phoBC2Eta_2);
    if (t->GetBranch("pho_ecalClusterIsoR2_2"))  t->SetBranchAddress("pho_ecalClusterIsoR2_2", &tdiphoton.pho_ecalClusterIsoR2_2, &tdiphoton.b_pho_ecalClusterIsoR2_2);
    if (t->GetBranch("pho_ecalClusterIsoR3_2"))  t->SetBranchAddress("pho_ecalClusterIsoR3_2", &tdiphoton.pho_ecalClusterIsoR3_2, &tdiphoton.b_pho_ecalClusterIsoR3_2);
    if (t->GetBranch("pho_ecalClusterIsoR4_2"))  t->SetBranchAddress("pho_ecalClusterIsoR4_2", &tdiphoton.pho_ecalClusterIsoR4_2, &tdiphoton.b_pho_ecalClusterIsoR4_2);
    if (t->GetBranch("pho_ecalClusterIsoR5_2"))  t->SetBranchAddress("pho_ecalClusterIsoR5_2", &tdiphoton.pho_ecalClusterIsoR5_2, &tdiphoton.b_pho_ecalClusterIsoR5_2);
    if (t->GetBranch("pho_hcalRechitIsoR1_2"))  t->SetBranchAddress("pho_hcalRechitIsoR1_2", &tdiphoton.pho_hcalRechitIsoR1_2, &tdiphoton.b_pho_hcalRechitIsoR1_2);
    if (t->GetBranch("pho_hcalRechitIsoR2_2"))  t->SetBranchAddress("pho_hcalRechitIsoR2_2", &tdiphoton.pho_hcalRechitIsoR2_2, &tdiphoton.b_pho_hcalRechitIsoR2_2);
    if (t->GetBranch("pho_hcalRechitIsoR3_2"))  t->SetBranchAddress("pho_hcalRechitIsoR3_2", &tdiphoton.pho_hcalRechitIsoR3_2, &tdiphoton.b_pho_hcalRechitIsoR3_2);
    if (t->GetBranch("pho_hcalRechitIsoR4_2"))  t->SetBranchAddress("pho_hcalRechitIsoR4_2", &tdiphoton.pho_hcalRechitIsoR4_2, &tdiphoton.b_pho_hcalRechitIsoR4_2);
    if (t->GetBranch("pho_hcalRechitIsoR5_2"))  t->SetBranchAddress("pho_hcalRechitIsoR5_2", &tdiphoton.pho_hcalRechitIsoR5_2, &tdiphoton.b_pho_hcalRechitIsoR5_2);
    if (t->GetBranch("pho_trackIsoR1PtCut20_2"))  t->SetBranchAddress("pho_trackIsoR1PtCut20_2", &tdiphoton.pho_trackIsoR1PtCut20_2, &tdiphoton.b_pho_trackIsoR1PtCut20_2);
    if (t->GetBranch("pho_trackIsoR2PtCut20_2"))  t->SetBranchAddress("pho_trackIsoR2PtCut20_2", &tdiphoton.pho_trackIsoR2PtCut20_2, &tdiphoton.b_pho_trackIsoR2PtCut20_2);
    if (t->GetBranch("pho_trackIsoR3PtCut20_2"))  t->SetBranchAddress("pho_trackIsoR3PtCut20_2", &tdiphoton.pho_trackIsoR3PtCut20_2, &tdiphoton.b_pho_trackIsoR3PtCut20_2);
    if (t->GetBranch("pho_trackIsoR4PtCut20_2"))  t->SetBranchAddress("pho_trackIsoR4PtCut20_2", &tdiphoton.pho_trackIsoR4PtCut20_2, &tdiphoton.b_pho_trackIsoR4PtCut20_2);
    if (t->GetBranch("pho_trackIsoR5PtCut20_2"))  t->SetBranchAddress("pho_trackIsoR5PtCut20_2", &tdiphoton.pho_trackIsoR5PtCut20_2, &tdiphoton.b_pho_trackIsoR5PtCut20_2);
    if (t->GetBranch("pho_swissCrx_2"))  t->SetBranchAddress("pho_swissCrx_2", &tdiphoton.pho_swissCrx_2, &tdiphoton.b_pho_swissCrx_2);
    if (t->GetBranch("pho_seedTime_2"))  t->SetBranchAddress("pho_seedTime_2", &tdiphoton.pho_seedTime_2, &tdiphoton.b_pho_seedTime_2);
    if (t->GetBranch("matched_eleCharge_2"))  t->SetBranchAddress("matched_eleCharge_2", &tdiphoton.matched_eleCharge_2, &tdiphoton.b_matched_eleCharge_2);
    if (t->GetBranch("matched_eleIndex_2"))  t->SetBranchAddress("matched_eleIndex_2", &tdiphoton.matched_eleIndex_2, &tdiphoton.b_matched_eleIndex_2);
    if (t->GetBranch("matched_elePt_2"))  t->SetBranchAddress("matched_elePt_2", &tdiphoton.matched_elePt_2, &tdiphoton.b_matched_elePt_2);
    if (t->GetBranch("matched_eleEta_2"))  t->SetBranchAddress("matched_eleEta_2", &tdiphoton.matched_eleEta_2, &tdiphoton.b_matched_eleEta_2);
    if (t->GetBranch("matched_elePhi_2"))  t->SetBranchAddress("matched_elePhi_2", &tdiphoton.matched_elePhi_2, &tdiphoton.b_matched_elePhi_2);
    if (t->GetBranch("matched_eleTrkPt_2"))  t->SetBranchAddress("matched_eleTrkPt_2", &tdiphoton.matched_eleTrkPt_2, &tdiphoton.b_matched_eleTrkPt_2);

    if (t->GetBranch("diPhoM"))  t->SetBranchAddress("diPhoM", &tdiphoton.diPhoM, &tdiphoton.b_diPhoM);
    if (t->GetBranch("diPhoEn"))  t->SetBranchAddress("diPhoEn", &tdiphoton.diPhoEn, &tdiphoton.b_diPhoEn);
    if (t->GetBranch("diPhoPt"))  t->SetBranchAddress("diPhoPt", &tdiphoton.diPhoPt, &tdiphoton.b_diPhoPt);
    if (t->GetBranch("diPhoEta"))  t->SetBranchAddress("diPhoEta", &tdiphoton.diPhoEta, &tdiphoton.b_diPhoEta);
    if (t->GetBranch("diPhoPhi"))  t->SetBranchAddress("diPhoPhi", &tdiphoton.diPhoPhi, &tdiphoton.b_diPhoPhi);
}

void branchDiPhotonTree(TTree *t,diphoton &tdiphoton)
{
    t->Branch("nPho", &tdiphoton.nPho_out);

    t->Branch("phoE_1", &tdiphoton.phoE_1_out);
    t->Branch("phoEt_1", &tdiphoton.phoEt_1_out);
    t->Branch("phoEta_1", &tdiphoton.phoEta_1_out);
    t->Branch("phoPhi_1", &tdiphoton.phoPhi_1_out);
    t->Branch("phoSCE_1", &tdiphoton.phoSCE_1_out);
    t->Branch("phoSCRawE_1", &tdiphoton.phoSCRawE_1_out);
    t->Branch("phoESEn_1", &tdiphoton.phoESEn_1_out);
    t->Branch("phoSCEta_1", &tdiphoton.phoSCEta_1_out);
    t->Branch("phoSCPhi_1", &tdiphoton.phoSCPhi_1_out);
    t->Branch("phoSCEtaWidth_1", &tdiphoton.phoSCEtaWidth_1_out);
    t->Branch("phoSCPhiWidth_1", &tdiphoton.phoSCPhiWidth_1_out);
    t->Branch("phoSCBrem_1", &tdiphoton.phoSCBrem_1_out);
    t->Branch("phohasPixelSeed_1", &tdiphoton.phohasPixelSeed_1_out);
    t->Branch("phoR9_1", &tdiphoton.phoR9_1_out);
    t->Branch("phoHoverE_1", &tdiphoton.phoHoverE_1_out);
    t->Branch("phoSigmaIEtaIEta_1", &tdiphoton.phoSigmaIEtaIEta_1_out);
    t->Branch("phoE1x3_1", &tdiphoton.phoE1x3_1_out);
    t->Branch("phoE2x2_1", &tdiphoton.phoE2x2_1_out);
    t->Branch("phoE3x3_1", &tdiphoton.phoE3x3_1_out);
    t->Branch("phoE2x5Max_1", &tdiphoton.phoE2x5Max_1_out);
    t->Branch("phoE1x5_1", &tdiphoton.phoE1x5_1_out);
    t->Branch("phoE2x5_1", &tdiphoton.phoE2x5_1_out);
    t->Branch("phoE5x5_1", &tdiphoton.phoE5x5_1_out);
    t->Branch("phoMaxEnergyXtal_1", &tdiphoton.phoMaxEnergyXtal_1_out);
    t->Branch("phoSigmaEtaEta_1", &tdiphoton.phoSigmaEtaEta_1_out);
    t->Branch("phoR1x5_1", &tdiphoton.phoR1x5_1_out);
    t->Branch("phoR2x5_1", &tdiphoton.phoR2x5_1_out);
    t->Branch("phoESEffSigmaRR_1", &tdiphoton.phoESEffSigmaRR_1_out);
    t->Branch("phoSigmaIEtaIEta_2012_1", &tdiphoton.phoSigmaIEtaIEta_2012_1_out);
    t->Branch("phoSigmaIEtaIPhi_2012_1", &tdiphoton.phoSigmaIEtaIPhi_2012_1_out);
    t->Branch("phoSigmaIPhiIPhi_2012_1", &tdiphoton.phoSigmaIPhiIPhi_2012_1_out);
    t->Branch("phoE1x3_2012_1", &tdiphoton.phoE1x3_2012_1_out);
    t->Branch("phoE2x2_2012_1", &tdiphoton.phoE2x2_2012_1_out);
    t->Branch("phoE3x3_2012_1", &tdiphoton.phoE3x3_2012_1_out);
    t->Branch("phoE2x5Max_2012_1", &tdiphoton.phoE2x5Max_2012_1_out);
    t->Branch("phoE5x5_2012_1", &tdiphoton.phoE5x5_2012_1_out);
    t->Branch("phoBC1E_1", &tdiphoton.phoBC1E_1_out);
    t->Branch("phoBC1Eta_1", &tdiphoton.phoBC1Eta_1_out);
    t->Branch("phoBC2E_1", &tdiphoton.phoBC2E_1_out);
    t->Branch("phoBC2Eta_1", &tdiphoton.phoBC2Eta_1_out);
    t->Branch("pho_ecalClusterIsoR2_1", &tdiphoton.pho_ecalClusterIsoR2_1_out);
    t->Branch("pho_ecalClusterIsoR3_1", &tdiphoton.pho_ecalClusterIsoR3_1_out);
    t->Branch("pho_ecalClusterIsoR4_1", &tdiphoton.pho_ecalClusterIsoR4_1_out);
    t->Branch("pho_ecalClusterIsoR5_1", &tdiphoton.pho_ecalClusterIsoR5_1_out);
    t->Branch("pho_hcalRechitIsoR1_1", &tdiphoton.pho_hcalRechitIsoR1_1_out);
    t->Branch("pho_hcalRechitIsoR2_1", &tdiphoton.pho_hcalRechitIsoR2_1_out);
    t->Branch("pho_hcalRechitIsoR3_1", &tdiphoton.pho_hcalRechitIsoR3_1_out);
    t->Branch("pho_hcalRechitIsoR4_1", &tdiphoton.pho_hcalRechitIsoR4_1_out);
    t->Branch("pho_hcalRechitIsoR5_1", &tdiphoton.pho_hcalRechitIsoR5_1_out);
    t->Branch("pho_trackIsoR1PtCut20_1", &tdiphoton.pho_trackIsoR1PtCut20_1_out);
    t->Branch("pho_trackIsoR2PtCut20_1", &tdiphoton.pho_trackIsoR2PtCut20_1_out);
    t->Branch("pho_trackIsoR3PtCut20_1", &tdiphoton.pho_trackIsoR3PtCut20_1_out);
    t->Branch("pho_trackIsoR4PtCut20_1", &tdiphoton.pho_trackIsoR4PtCut20_1_out);
    t->Branch("pho_trackIsoR5PtCut20_1", &tdiphoton.pho_trackIsoR5PtCut20_1_out);
    t->Branch("pho_swissCrx_1", &tdiphoton.pho_swissCrx_1_out);
    t->Branch("pho_seedTime_1", &tdiphoton.pho_seedTime_1_out);
    t->Branch("matched_eleCharge_1", &tdiphoton.matched_eleCharge_1_out);
    t->Branch("matched_eleIndex_1", &tdiphoton.matched_eleIndex_1_out);
    t->Branch("matched_elePt_1", &tdiphoton.matched_elePt_1_out);
    t->Branch("matched_eleEta_1", &tdiphoton.matched_eleEta_1_out);
    t->Branch("matched_eleTrkPt_1", &tdiphoton.matched_eleTrkPt_1_out);

    t->Branch("phoE_2", &tdiphoton.phoE_2_out);
    t->Branch("phoEt_2", &tdiphoton.phoEt_2_out);
    t->Branch("phoEta_2", &tdiphoton.phoEta_2_out);
    t->Branch("phoPhi_2", &tdiphoton.phoPhi_2_out);
    t->Branch("phoSCE_2", &tdiphoton.phoSCE_2_out);
    t->Branch("phoSCRawE_2", &tdiphoton.phoSCRawE_2_out);
    t->Branch("phoESEn_2", &tdiphoton.phoESEn_2_out);
    t->Branch("phoSCEta_2", &tdiphoton.phoSCEta_2_out);
    t->Branch("phoSCPhi_2", &tdiphoton.phoSCPhi_2_out);
    t->Branch("phoSCEtaWidth_2", &tdiphoton.phoSCEtaWidth_2_out);
    t->Branch("phoSCPhiWidth_2", &tdiphoton.phoSCPhiWidth_2_out);
    t->Branch("phoSCBrem_2", &tdiphoton.phoSCBrem_2_out);
    t->Branch("phohasPixelSeed_2", &tdiphoton.phohasPixelSeed_2_out);
    t->Branch("phoR9_2", &tdiphoton.phoR9_2_out);
    t->Branch("phoHoverE_2", &tdiphoton.phoHoverE_2_out);
    t->Branch("phoSigmaIEtaIEta_2", &tdiphoton.phoSigmaIEtaIEta_2_out);
    t->Branch("phoE1x3_2", &tdiphoton.phoE1x3_2_out);
    t->Branch("phoE2x2_2", &tdiphoton.phoE2x2_2_out);
    t->Branch("phoE3x3_2", &tdiphoton.phoE3x3_2_out);
    t->Branch("phoE2x5Max_2", &tdiphoton.phoE2x5Max_2_out);
    t->Branch("phoE1x5_2", &tdiphoton.phoE1x5_2_out);
    t->Branch("phoE2x5_2", &tdiphoton.phoE2x5_2_out);
    t->Branch("phoE5x5_2", &tdiphoton.phoE5x5_2_out);
    t->Branch("phoMaxEnergyXtal_2", &tdiphoton.phoMaxEnergyXtal_2_out);
    t->Branch("phoSigmaEtaEta_2", &tdiphoton.phoSigmaEtaEta_2_out);
    t->Branch("phoR1x5_2", &tdiphoton.phoR1x5_2_out);
    t->Branch("phoR2x5_2", &tdiphoton.phoR2x5_2_out);
    t->Branch("phoESEffSigmaRR_2", &tdiphoton.phoESEffSigmaRR_2_out);
    t->Branch("phoSigmaIEtaIEta_2012_2", &tdiphoton.phoSigmaIEtaIEta_2012_2_out);
    t->Branch("phoSigmaIEtaIPhi_2012_2", &tdiphoton.phoSigmaIEtaIPhi_2012_2_out);
    t->Branch("phoSigmaIPhiIPhi_2012_2", &tdiphoton.phoSigmaIPhiIPhi_2012_2_out);
    t->Branch("phoE1x3_2012_2", &tdiphoton.phoE1x3_2012_2_out);
    t->Branch("phoE2x2_2012_2", &tdiphoton.phoE2x2_2012_2_out);
    t->Branch("phoE3x3_2012_2", &tdiphoton.phoE3x3_2012_2_out);
    t->Branch("phoE2x5Max_2012_2", &tdiphoton.phoE2x5Max_2012_2_out);
    t->Branch("phoE5x5_2012_2", &tdiphoton.phoE5x5_2012_2_out);
    t->Branch("phoBC1E_2", &tdiphoton.phoBC1E_2_out);
    t->Branch("phoBC1Eta_2", &tdiphoton.phoBC1Eta_2_out);
    t->Branch("phoBC2E_2", &tdiphoton.phoBC2E_2_out);
    t->Branch("phoBC2Eta_2", &tdiphoton.phoBC2Eta_2_out);
    t->Branch("pho_ecalClusterIsoR2_2", &tdiphoton.pho_ecalClusterIsoR2_2_out);
    t->Branch("pho_ecalClusterIsoR3_2", &tdiphoton.pho_ecalClusterIsoR3_2_out);
    t->Branch("pho_ecalClusterIsoR4_2", &tdiphoton.pho_ecalClusterIsoR4_2_out);
    t->Branch("pho_ecalClusterIsoR5_2", &tdiphoton.pho_ecalClusterIsoR5_2_out);
    t->Branch("pho_hcalRechitIsoR1_2", &tdiphoton.pho_hcalRechitIsoR1_2_out);
    t->Branch("pho_hcalRechitIsoR2_2", &tdiphoton.pho_hcalRechitIsoR2_2_out);
    t->Branch("pho_hcalRechitIsoR3_2", &tdiphoton.pho_hcalRechitIsoR3_2_out);
    t->Branch("pho_hcalRechitIsoR4_2", &tdiphoton.pho_hcalRechitIsoR4_2_out);
    t->Branch("pho_hcalRechitIsoR5_2", &tdiphoton.pho_hcalRechitIsoR5_2_out);
    t->Branch("pho_trackIsoR1PtCut20_2", &tdiphoton.pho_trackIsoR1PtCut20_2_out);
    t->Branch("pho_trackIsoR2PtCut20_2", &tdiphoton.pho_trackIsoR2PtCut20_2_out);
    t->Branch("pho_trackIsoR3PtCut20_2", &tdiphoton.pho_trackIsoR3PtCut20_2_out);
    t->Branch("pho_trackIsoR4PtCut20_2", &tdiphoton.pho_trackIsoR4PtCut20_2_out);
    t->Branch("pho_trackIsoR5PtCut20_2", &tdiphoton.pho_trackIsoR5PtCut20_2_out);
    t->Branch("pho_swissCrx_2", &tdiphoton.pho_swissCrx_2_out);
    t->Branch("pho_seedTime_2", &tdiphoton.pho_seedTime_2_out);
    t->Branch("matched_eleCharge_2", &tdiphoton.matched_eleCharge_2_out);
    t->Branch("matched_eleIndex_2", &tdiphoton.matched_eleIndex_2_out);
    t->Branch("matched_elePt_2", &tdiphoton.matched_elePt_2_out);
    t->Branch("matched_eleEta_2", &tdiphoton.matched_eleEta_2_out);
    t->Branch("matched_eleTrkPt_2", &tdiphoton.matched_eleTrkPt_2_out);

    t->Branch("diPhoM", &tdiphoton.diPhoM_out);
    t->Branch("diPhoEn", &tdiphoton.diPhoEn_out);
    t->Branch("diPhoPt", &tdiphoton.diPhoPt_out);
    t->Branch("diPhoEta", &tdiphoton.diPhoEta_out);
    t->Branch("diPhoPhi", &tdiphoton.diPhoPhi_out);
}

void makeDiPhotonPairs(ggHiNtuplizer &tggHiNtuplizer, diphoton &tdiphoton, bool doEleMatch, bool doSizeCheck)
{

    tdiphoton.phoE_1_out.clear();
    tdiphoton.phoEt_1_out.clear();
    tdiphoton.phoEta_1_out.clear();
    tdiphoton.phoPhi_1_out.clear();
    tdiphoton.phoSCE_1_out.clear();
    tdiphoton.phoSCRawE_1_out.clear();
    tdiphoton.phoESEn_1_out.clear();
    tdiphoton.phoSCEta_1_out.clear();
    tdiphoton.phoSCPhi_1_out.clear();
    tdiphoton.phoSCEtaWidth_1_out.clear();
    tdiphoton.phoSCPhiWidth_1_out.clear();
    tdiphoton.phoSCBrem_1_out.clear();
    tdiphoton.phohasPixelSeed_1_out.clear();
    tdiphoton.phoR9_1_out.clear();
    tdiphoton.phoHoverE_1_out.clear();
    tdiphoton.phoSigmaIEtaIEta_1_out.clear();
    tdiphoton.phoE1x3_1_out.clear();
    tdiphoton.phoE2x2_1_out.clear();
    tdiphoton.phoE3x3_1_out.clear();
    tdiphoton.phoE2x5Max_1_out.clear();
    tdiphoton.phoE1x5_1_out.clear();
    tdiphoton.phoE2x5_1_out.clear();
    tdiphoton.phoE5x5_1_out.clear();
    tdiphoton.phoMaxEnergyXtal_1_out.clear();
    tdiphoton.phoSigmaEtaEta_1_out.clear();
    tdiphoton.phoR1x5_1_out.clear();
    tdiphoton.phoR2x5_1_out.clear();
    tdiphoton.phoESEffSigmaRR_1_out.clear();
    tdiphoton.phoSigmaIEtaIEta_2012_1_out.clear();
    tdiphoton.phoSigmaIEtaIPhi_2012_1_out.clear();
    tdiphoton.phoSigmaIPhiIPhi_2012_1_out.clear();
    tdiphoton.phoE1x3_2012_1_out.clear();
    tdiphoton.phoE2x2_2012_1_out.clear();
    tdiphoton.phoE3x3_2012_1_out.clear();
    tdiphoton.phoE2x5Max_2012_1_out.clear();
    tdiphoton.phoE5x5_2012_1_out.clear();
    tdiphoton.phoBC1E_1_out.clear();
    tdiphoton.phoBC1Eta_1_out.clear();
    tdiphoton.phoBC2E_1_out.clear();
    tdiphoton.phoBC2Eta_1_out.clear();
    tdiphoton.pho_ecalClusterIsoR2_1_out.clear();
    tdiphoton.pho_ecalClusterIsoR3_1_out.clear();
    tdiphoton.pho_ecalClusterIsoR4_1_out.clear();
    tdiphoton.pho_ecalClusterIsoR5_1_out.clear();
    tdiphoton.pho_hcalRechitIsoR1_1_out.clear();
    tdiphoton.pho_hcalRechitIsoR2_1_out.clear();
    tdiphoton.pho_hcalRechitIsoR3_1_out.clear();
    tdiphoton.pho_hcalRechitIsoR4_1_out.clear();
    tdiphoton.pho_hcalRechitIsoR5_1_out.clear();
    tdiphoton.pho_trackIsoR1PtCut20_1_out.clear();
    tdiphoton.pho_trackIsoR2PtCut20_1_out.clear();
    tdiphoton.pho_trackIsoR3PtCut20_1_out.clear();
    tdiphoton.pho_trackIsoR4PtCut20_1_out.clear();
    tdiphoton.pho_trackIsoR5PtCut20_1_out.clear();
    tdiphoton.pho_swissCrx_1_out.clear();
    tdiphoton.pho_seedTime_1_out.clear();
    tdiphoton.matched_eleCharge_1_out.clear();
    tdiphoton.matched_eleIndex_1_out.clear();
    tdiphoton.matched_elePt_1_out.clear();
    tdiphoton.matched_eleEta_1_out.clear();
    tdiphoton.matched_elePhi_1_out.clear();
    tdiphoton.matched_eleTrkPt_1_out.clear();

    tdiphoton.phoE_2_out.clear();
    tdiphoton.phoEt_2_out.clear();
    tdiphoton.phoEta_2_out.clear();
    tdiphoton.phoPhi_2_out.clear();
    tdiphoton.phoSCE_2_out.clear();
    tdiphoton.phoSCRawE_2_out.clear();
    tdiphoton.phoESEn_2_out.clear();
    tdiphoton.phoSCEta_2_out.clear();
    tdiphoton.phoSCPhi_2_out.clear();
    tdiphoton.phoSCEtaWidth_2_out.clear();
    tdiphoton.phoSCPhiWidth_2_out.clear();
    tdiphoton.phoSCBrem_2_out.clear();
    tdiphoton.phohasPixelSeed_2_out.clear();
    tdiphoton.phoR9_2_out.clear();
    tdiphoton.phoHoverE_2_out.clear();
    tdiphoton.phoSigmaIEtaIEta_2_out.clear();
    tdiphoton.phoE1x3_2_out.clear();
    tdiphoton.phoE2x2_2_out.clear();
    tdiphoton.phoE3x3_2_out.clear();
    tdiphoton.phoE2x5Max_2_out.clear();
    tdiphoton.phoE1x5_2_out.clear();
    tdiphoton.phoE2x5_2_out.clear();
    tdiphoton.phoE5x5_2_out.clear();
    tdiphoton.phoMaxEnergyXtal_2_out.clear();
    tdiphoton.phoSigmaEtaEta_2_out.clear();
    tdiphoton.phoR1x5_2_out.clear();
    tdiphoton.phoR2x5_2_out.clear();
    tdiphoton.phoESEffSigmaRR_2_out.clear();
    tdiphoton.phoSigmaIEtaIEta_2012_2_out.clear();
    tdiphoton.phoSigmaIEtaIPhi_2012_2_out.clear();
    tdiphoton.phoSigmaIPhiIPhi_2012_2_out.clear();
    tdiphoton.phoE1x3_2012_2_out.clear();
    tdiphoton.phoE2x2_2012_2_out.clear();
    tdiphoton.phoE3x3_2012_2_out.clear();
    tdiphoton.phoE2x5Max_2012_2_out.clear();
    tdiphoton.phoE5x5_2012_2_out.clear();
    tdiphoton.phoBC1E_2_out.clear();
    tdiphoton.phoBC1Eta_2_out.clear();
    tdiphoton.phoBC2E_2_out.clear();
    tdiphoton.phoBC2Eta_2_out.clear();
    tdiphoton.pho_ecalClusterIsoR2_2_out.clear();
    tdiphoton.pho_ecalClusterIsoR3_2_out.clear();
    tdiphoton.pho_ecalClusterIsoR4_2_out.clear();
    tdiphoton.pho_ecalClusterIsoR5_2_out.clear();
    tdiphoton.pho_hcalRechitIsoR1_2_out.clear();
    tdiphoton.pho_hcalRechitIsoR2_2_out.clear();
    tdiphoton.pho_hcalRechitIsoR3_2_out.clear();
    tdiphoton.pho_hcalRechitIsoR4_2_out.clear();
    tdiphoton.pho_hcalRechitIsoR5_2_out.clear();
    tdiphoton.pho_trackIsoR1PtCut20_2_out.clear();
    tdiphoton.pho_trackIsoR2PtCut20_2_out.clear();
    tdiphoton.pho_trackIsoR3PtCut20_2_out.clear();
    tdiphoton.pho_trackIsoR4PtCut20_2_out.clear();
    tdiphoton.pho_trackIsoR5PtCut20_2_out.clear();
    tdiphoton.pho_swissCrx_2_out.clear();
    tdiphoton.pho_seedTime_2_out.clear();
    tdiphoton.matched_eleCharge_2_out.clear();
    tdiphoton.matched_eleIndex_2_out.clear();
    tdiphoton.matched_elePt_2_out.clear();
    tdiphoton.matched_eleEta_2_out.clear();
    tdiphoton.matched_elePhi_2_out.clear();
    tdiphoton.matched_eleTrkPt_2_out.clear();

    tdiphoton.diPhoM_out.clear();
    tdiphoton.diPhoEn_out.clear();
    tdiphoton.diPhoPt_out.clear();
    tdiphoton.diPhoEta_out.clear();
    tdiphoton.diPhoPhi_out.clear();

    std::vector<int>   matched_eleCharge_tmp;
    std::vector<int>   matched_eleIndex_tmp;
    std::vector<float> matched_elePt_tmp;
    std::vector<float> matched_eleEta_tmp;
    std::vector<float> matched_elePhi_tmp;
    std::vector<float> matched_eleTrkPt_tmp;

    matched_eleCharge_tmp.clear();
    matched_eleIndex_tmp.clear();
    matched_elePt_tmp.clear();
    matched_eleEta_tmp.clear();
    matched_elePhi_tmp.clear();
    matched_eleTrkPt_tmp.clear();

    tdiphoton.nPho_out = tggHiNtuplizer.nPho;
    if (doEleMatch) {
        // electron-photon matching
        // based on  https://github.com/CmsHI/HiForestAnalysis/blob/master/PhotonUtilities.C#L154-L186
        for(int i=0; i< tdiphoton.nPho_out; ++i) {
            float currentMaxPt=-1;
            int matched_Index =-1;
            for (int j=0; j< tggHiNtuplizer.nEle; ++j) {
                if (tggHiNtuplizer.elePt->at(j) < currentMaxPt) continue;
                if (getDR(tggHiNtuplizer.eleEta->at(j), tggHiNtuplizer.elePhi->at(j), tggHiNtuplizer.phoEta->at(i), tggHiNtuplizer.phoPhi->at(i))>tdiphoton.cutDeltaR) continue;

                matched_Index=j;
                currentMaxPt=tggHiNtuplizer.elePt->at(j);
            }
            matched_eleIndex_tmp.push_back(matched_Index);

            if (matched_Index > -1) {
                matched_eleCharge_tmp.push_back(tggHiNtuplizer.eleCharge->at(matched_Index));
                matched_elePt_tmp.push_back(tggHiNtuplizer.elePt->at(matched_Index));
                matched_eleEta_tmp.push_back(tggHiNtuplizer.eleEta->at(matched_Index));
                matched_elePhi_tmp.push_back(tggHiNtuplizer.elePhi->at(matched_Index));
                matched_eleTrkPt_tmp.push_back(tggHiNtuplizer.eleTrkPt->at(matched_Index));
            } else {
                matched_eleCharge_tmp.push_back(0);
                matched_elePt_tmp.push_back(-1);
                matched_eleEta_tmp.push_back(0);
                matched_elePhi_tmp.push_back(0);
                matched_eleTrkPt_tmp.push_back(-1);
            }
        }
    }
    else {
        for(int i=0; i< tdiphoton.nPho_out; ++i) {
            matched_eleCharge_tmp.push_back(0);
            matched_elePt_tmp.push_back(-1);
            matched_eleEta_tmp.push_back(0);
            matched_elePhi_tmp.push_back(0);
            matched_eleTrkPt_tmp.push_back(-1);
        }
    }

    for(int i=0; i<tdiphoton.nPho_out; ++i)
    {
        for(int j=i+1; j<tdiphoton.nPho_out; ++j)
        {
            if (doSizeCheck) {

                if(tggHiNtuplizer.phoE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE_1_out.push_back(tggHiNtuplizer.phoE->at(i));
                if(tggHiNtuplizer.phoEt->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoEt_1_out.push_back(tggHiNtuplizer.phoEt->at(i));
                if(tggHiNtuplizer.phoEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoEta_1_out.push_back(tggHiNtuplizer.phoEta->at(i));
                if(tggHiNtuplizer.phoPhi->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoPhi_1_out.push_back(tggHiNtuplizer.phoPhi->at(i));
                if(tggHiNtuplizer.phoSCE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCE_1_out.push_back(tggHiNtuplizer.phoSCE->at(i));
                if(tggHiNtuplizer.phoSCRawE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCRawE_1_out.push_back(tggHiNtuplizer.phoSCRawE->at(i));
                if(tggHiNtuplizer.phoESEn->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoESEn_1_out.push_back(tggHiNtuplizer.phoESEn->at(i));
                if(tggHiNtuplizer.phoSCEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCEta_1_out.push_back(tggHiNtuplizer.phoSCEta->at(i));
                if(tggHiNtuplizer.phoSCPhi->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCPhi_1_out.push_back(tggHiNtuplizer.phoSCPhi->at(i));
                if(tggHiNtuplizer.phoSCEtaWidth->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCEtaWidth_1_out.push_back(tggHiNtuplizer.phoSCEtaWidth->at(i));
                if(tggHiNtuplizer.phoSCPhiWidth->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCPhiWidth_1_out.push_back(tggHiNtuplizer.phoSCPhiWidth->at(i));
                if(tggHiNtuplizer.phoSCBrem->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCBrem_1_out.push_back(tggHiNtuplizer.phoSCBrem->at(i));
                if(tggHiNtuplizer.phohasPixelSeed->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phohasPixelSeed_1_out.push_back(tggHiNtuplizer.phohasPixelSeed->at(i));
                if(tggHiNtuplizer.phoR9->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR9_1_out.push_back(tggHiNtuplizer.phoR9->at(i));
                if(tggHiNtuplizer.phoHoverE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoHoverE_1_out.push_back(tggHiNtuplizer.phoHoverE->at(i));
                if(tggHiNtuplizer.phoSigmaIEtaIEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIEta_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta->at(i));
                if(tggHiNtuplizer.phoE1x3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x3_1_out.push_back(tggHiNtuplizer.phoE1x3->at(i));
                if(tggHiNtuplizer.phoE2x2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x2_1_out.push_back(tggHiNtuplizer.phoE2x2->at(i));
//                if(tggHiNtuplizer.phoE3x3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE3x3_1_out.push_back(tggHiNtuplizer.phoE3x3->at(i));
                if(tggHiNtuplizer.phoE2x5Max->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5Max_1_out.push_back(tggHiNtuplizer.phoE2x5Max->at(i));
//                if(tggHiNtuplizer.phoE1x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x5_1_out.push_back(tggHiNtuplizer.phoE1x5->at(i));
//                if(tggHiNtuplizer.phoE2x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5_1_out.push_back(tggHiNtuplizer.phoE2x5->at(i));
                if(tggHiNtuplizer.phoE5x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE5x5_1_out.push_back(tggHiNtuplizer.phoE5x5->at(i));
//                if(tggHiNtuplizer.phoMaxEnergyXtal->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoMaxEnergyXtal_1_out.push_back(tggHiNtuplizer.phoMaxEnergyXtal->at(i));
//                if(tggHiNtuplizer.phoSigmaEtaEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaEtaEta_1_out.push_back(tggHiNtuplizer.phoSigmaEtaEta->at(i));
//                if(tggHiNtuplizer.phoR1x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR1x5_1_out.push_back(tggHiNtuplizer.phoR1x5->at(i));
//                if(tggHiNtuplizer.phoR2x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR2x5_1_out.push_back(tggHiNtuplizer.phoR2x5->at(i));
                if(tggHiNtuplizer.phoESEffSigmaRR->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoESEffSigmaRR_1_out.push_back(tggHiNtuplizer.phoESEffSigmaRR->at(i));
                if(tggHiNtuplizer.phoSigmaIEtaIEta_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIEta_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta_2012->at(i));
                if(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIPhi_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->at(i));
                if(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIPhiIPhi_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->at(i));
                if(tggHiNtuplizer.phoE1x3_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x3_2012_1_out.push_back(tggHiNtuplizer.phoE1x3_2012->at(i));
                if(tggHiNtuplizer.phoE2x2_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x2_2012_1_out.push_back(tggHiNtuplizer.phoE2x2_2012->at(i));
//                if(tggHiNtuplizer.phoE3x3_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE3x3_2012_1_out.push_back(tggHiNtuplizer.phoE3x3_2012->at(i));
                if(tggHiNtuplizer.phoE2x5Max_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5Max_2012_1_out.push_back(tggHiNtuplizer.phoE2x5Max_2012->at(i));
                if(tggHiNtuplizer.phoE5x5_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE5x5_2012_1_out.push_back(tggHiNtuplizer.phoE5x5_2012->at(i));
                if(tggHiNtuplizer.phoBC1E->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC1E_1_out.push_back(tggHiNtuplizer.phoBC1E->at(i));
                if(tggHiNtuplizer.phoBC1Eta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC1Eta_1_out.push_back(tggHiNtuplizer.phoBC1Eta->at(i));
                if(tggHiNtuplizer.phoBC2E->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC2E_1_out.push_back(tggHiNtuplizer.phoBC2E->at(i));
                if(tggHiNtuplizer.phoBC2Eta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC2Eta_1_out.push_back(tggHiNtuplizer.phoBC2Eta->at(i));
                if(tggHiNtuplizer.pho_ecalClusterIsoR2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR2_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR2->at(i));
                if(tggHiNtuplizer.pho_ecalClusterIsoR3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR3_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR3->at(i));
                if(tggHiNtuplizer.pho_ecalClusterIsoR4->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR4_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR4->at(i));
                if(tggHiNtuplizer.pho_ecalClusterIsoR5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR5_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR5->at(i));
                if(tggHiNtuplizer.pho_hcalRechitIsoR1->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR1_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR1->at(i));
                if(tggHiNtuplizer.pho_hcalRechitIsoR2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR2_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR2->at(i));
                if(tggHiNtuplizer.pho_hcalRechitIsoR3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR3_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR3->at(i));
                if(tggHiNtuplizer.pho_hcalRechitIsoR4->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR4_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR4->at(i));
                if(tggHiNtuplizer.pho_hcalRechitIsoR5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR5_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR5->at(i));
                if(tggHiNtuplizer.pho_trackIsoR1PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR1PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR1PtCut20->at(i));
                if(tggHiNtuplizer.pho_trackIsoR2PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR2PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR2PtCut20->at(i));
                if(tggHiNtuplizer.pho_trackIsoR3PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR3PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR3PtCut20->at(i));
                if(tggHiNtuplizer.pho_trackIsoR4PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR4PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR4PtCut20->at(i));
                if(tggHiNtuplizer.pho_trackIsoR5PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR5PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR5PtCut20->at(i));
                if(tggHiNtuplizer.pho_swissCrx->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_swissCrx_1_out.push_back(tggHiNtuplizer.pho_swissCrx->at(i));
                if(tggHiNtuplizer.pho_seedTime->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_seedTime_1_out.push_back(tggHiNtuplizer.pho_seedTime->at(i));
                tdiphoton.matched_eleIndex_1_out.push_back(matched_eleIndex_tmp.at(i));
                tdiphoton.matched_eleCharge_1_out.push_back(matched_eleCharge_tmp.at(i));
                tdiphoton.matched_elePt_1_out.push_back(matched_elePt_tmp.at(i));
                tdiphoton.matched_eleEta_1_out.push_back(matched_eleEta_tmp.at(i));
                tdiphoton.matched_elePhi_1_out.push_back(matched_elePhi_tmp.at(i));
                tdiphoton.matched_eleTrkPt_1_out.push_back(matched_eleTrkPt_tmp.at(i));

                if(tggHiNtuplizer.phoE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE_2_out.push_back(tggHiNtuplizer.phoE->at(j));
                if(tggHiNtuplizer.phoEt->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoEt_2_out.push_back(tggHiNtuplizer.phoEt->at(j));
                if(tggHiNtuplizer.phoEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoEta_2_out.push_back(tggHiNtuplizer.phoEta->at(j));
                if(tggHiNtuplizer.phoPhi->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoPhi_2_out.push_back(tggHiNtuplizer.phoPhi->at(j));
                if(tggHiNtuplizer.phoSCE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCE_2_out.push_back(tggHiNtuplizer.phoSCE->at(j));
                if(tggHiNtuplizer.phoSCRawE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCRawE_2_out.push_back(tggHiNtuplizer.phoSCRawE->at(j));
                if(tggHiNtuplizer.phoESEn->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoESEn_2_out.push_back(tggHiNtuplizer.phoESEn->at(j));
                if(tggHiNtuplizer.phoSCEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCEta_2_out.push_back(tggHiNtuplizer.phoSCEta->at(j));
                if(tggHiNtuplizer.phoSCPhi->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCPhi_2_out.push_back(tggHiNtuplizer.phoSCPhi->at(j));
                if(tggHiNtuplizer.phoSCEtaWidth->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCEtaWidth_2_out.push_back(tggHiNtuplizer.phoSCEtaWidth->at(j));
                if(tggHiNtuplizer.phoSCPhiWidth->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCPhiWidth_2_out.push_back(tggHiNtuplizer.phoSCPhiWidth->at(j));
                if(tggHiNtuplizer.phoSCBrem->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSCBrem_2_out.push_back(tggHiNtuplizer.phoSCBrem->at(j));
                if(tggHiNtuplizer.phohasPixelSeed->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phohasPixelSeed_2_out.push_back(tggHiNtuplizer.phohasPixelSeed->at(j));
                if(tggHiNtuplizer.phoR9->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR9_2_out.push_back(tggHiNtuplizer.phoR9->at(j));
                if(tggHiNtuplizer.phoHoverE->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoHoverE_2_out.push_back(tggHiNtuplizer.phoHoverE->at(j));
                if(tggHiNtuplizer.phoSigmaIEtaIEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIEta_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta->at(j));
                if(tggHiNtuplizer.phoE1x3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x3_2_out.push_back(tggHiNtuplizer.phoE1x3->at(j));
                if(tggHiNtuplizer.phoE2x2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x2_2_out.push_back(tggHiNtuplizer.phoE2x2->at(j));
//                if(tggHiNtuplizer.phoE3x3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE3x3_2_out.push_back(tggHiNtuplizer.phoE3x3->at(j));
                if(tggHiNtuplizer.phoE2x5Max->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5Max_2_out.push_back(tggHiNtuplizer.phoE2x5Max->at(j));
//                if(tggHiNtuplizer.phoE1x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x5_2_out.push_back(tggHiNtuplizer.phoE1x5->at(j));
//                if(tggHiNtuplizer.phoE2x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5_2_out.push_back(tggHiNtuplizer.phoE2x5->at(j));
                if(tggHiNtuplizer.phoE5x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE5x5_2_out.push_back(tggHiNtuplizer.phoE5x5->at(j));
//                if(tggHiNtuplizer.phoMaxEnergyXtal->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoMaxEnergyXtal_2_out.push_back(tggHiNtuplizer.phoMaxEnergyXtal->at(j));
//                if(tggHiNtuplizer.phoSigmaEtaEta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaEtaEta_2_out.push_back(tggHiNtuplizer.phoSigmaEtaEta->at(j));
//                if(tggHiNtuplizer.phoR1x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR1x5_2_out.push_back(tggHiNtuplizer.phoR1x5->at(j));
//                if(tggHiNtuplizer.phoR2x5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoR2x5_2_out.push_back(tggHiNtuplizer.phoR2x5->at(j));
                if(tggHiNtuplizer.phoESEffSigmaRR->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoESEffSigmaRR_2_out.push_back(tggHiNtuplizer.phoESEffSigmaRR->at(j));
                if(tggHiNtuplizer.phoSigmaIEtaIEta_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIEta_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta_2012->at(j));
                if(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIEtaIPhi_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->at(j));
                if(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoSigmaIPhiIPhi_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->at(j));
                if(tggHiNtuplizer.phoE1x3_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE1x3_2012_2_out.push_back(tggHiNtuplizer.phoE1x3_2012->at(j));
                if(tggHiNtuplizer.phoE2x2_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x2_2012_2_out.push_back(tggHiNtuplizer.phoE2x2_2012->at(j));
//                if(tggHiNtuplizer.phoE3x3_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE3x3_2012_2_out.push_back(tggHiNtuplizer.phoE3x3_2012->at(j));
                if(tggHiNtuplizer.phoE2x5Max_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE2x5Max_2012_2_out.push_back(tggHiNtuplizer.phoE2x5Max_2012->at(j));
                if(tggHiNtuplizer.phoE5x5_2012->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoE5x5_2012_2_out.push_back(tggHiNtuplizer.phoE5x5_2012->at(j));
                if(tggHiNtuplizer.phoBC1E->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC1E_2_out.push_back(tggHiNtuplizer.phoBC1E->at(j));
                if(tggHiNtuplizer.phoBC1Eta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC1Eta_2_out.push_back(tggHiNtuplizer.phoBC1Eta->at(j));
                if(tggHiNtuplizer.phoBC2E->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC2E_2_out.push_back(tggHiNtuplizer.phoBC2E->at(j));
                if(tggHiNtuplizer.phoBC2Eta->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.phoBC2Eta_2_out.push_back(tggHiNtuplizer.phoBC2Eta->at(j));
                if(tggHiNtuplizer.pho_ecalClusterIsoR2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR2_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR2->at(j));
                if(tggHiNtuplizer.pho_ecalClusterIsoR3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR3_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR3->at(j));
                if(tggHiNtuplizer.pho_ecalClusterIsoR4->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR4_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR4->at(j));
                if(tggHiNtuplizer.pho_ecalClusterIsoR5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_ecalClusterIsoR5_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR5->at(j));
                if(tggHiNtuplizer.pho_hcalRechitIsoR1->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR1_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR1->at(j));
                if(tggHiNtuplizer.pho_hcalRechitIsoR2->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR2_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR2->at(j));
                if(tggHiNtuplizer.pho_hcalRechitIsoR3->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR3_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR3->at(j));
                if(tggHiNtuplizer.pho_hcalRechitIsoR4->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR4_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR4->at(j));
                if(tggHiNtuplizer.pho_hcalRechitIsoR5->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_hcalRechitIsoR5_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR5->at(j));
                if(tggHiNtuplizer.pho_trackIsoR1PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR1PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR1PtCut20->at(j));
                if(tggHiNtuplizer.pho_trackIsoR2PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR2PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR2PtCut20->at(j));
                if(tggHiNtuplizer.pho_trackIsoR3PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR3PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR3PtCut20->at(j));
                if(tggHiNtuplizer.pho_trackIsoR4PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR4PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR4PtCut20->at(j));
                if(tggHiNtuplizer.pho_trackIsoR5PtCut20->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_trackIsoR5PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR5PtCut20->at(j));
                if(tggHiNtuplizer.pho_swissCrx->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_swissCrx_2_out.push_back(tggHiNtuplizer.pho_swissCrx->at(j));
                if(tggHiNtuplizer.pho_seedTime->size() == (unsigned)tdiphoton.nPho_out)  tdiphoton.pho_seedTime_2_out.push_back(tggHiNtuplizer.pho_seedTime->at(j));
                tdiphoton.matched_eleIndex_2_out.push_back(matched_eleIndex_tmp.at(j));
                tdiphoton.matched_eleCharge_2_out.push_back(matched_eleCharge_tmp.at(j));
                tdiphoton.matched_elePt_2_out.push_back(matched_elePt_tmp.at(j));
                tdiphoton.matched_eleEta_2_out.push_back(matched_eleEta_tmp.at(j));
                tdiphoton.matched_elePhi_2_out.push_back(matched_elePhi_tmp.at(j));
                tdiphoton.matched_eleTrkPt_2_out.push_back(matched_eleTrkPt_tmp.at(j));

                // diphoton
                if (tggHiNtuplizer.phoEt->size()  == (unsigned)tdiphoton.nPho_out &&
                    tggHiNtuplizer.phoEta->size() == (unsigned)tdiphoton.nPho_out &&
                    tggHiNtuplizer.phoPhi->size() == (unsigned)tdiphoton.nPho_out)
                {
                    TLorentzVector v1, v2, vSum;
                    v1.SetPtEtaPhiE( tggHiNtuplizer.phoEt->at(i), tggHiNtuplizer.phoEta->at(i),
                            tggHiNtuplizer.phoPhi->at(i), tggHiNtuplizer.phoE->at(i));
                    v2.SetPtEtaPhiE( tggHiNtuplizer.phoEt->at(j), tggHiNtuplizer.phoEta->at(j),
                            tggHiNtuplizer.phoPhi->at(j), tggHiNtuplizer.phoE->at(j));
                    vSum = v1+v2;

                    tdiphoton.diPhoM_out.push_back(vSum.M());
                    tdiphoton.diPhoEn_out.push_back(vSum.Energy());
                    tdiphoton.diPhoPt_out.push_back(vSum.Pt());
                    tdiphoton.diPhoEta_out.push_back(vSum.Eta());
                    tdiphoton.diPhoPhi_out.push_back(vSum.Phi());
                }
            }
            else {
                tdiphoton.phoE_1_out.push_back(tggHiNtuplizer.phoE->at(i));
                tdiphoton.phoEt_1_out.push_back(tggHiNtuplizer.phoEt->at(i));
                tdiphoton.phoEta_1_out.push_back(tggHiNtuplizer.phoEta->at(i));
                tdiphoton.phoPhi_1_out.push_back(tggHiNtuplizer.phoPhi->at(i));
                tdiphoton.phoSCE_1_out.push_back(tggHiNtuplizer.phoSCE->at(i));
                tdiphoton.phoSCRawE_1_out.push_back(tggHiNtuplizer.phoSCRawE->at(i));
                tdiphoton.phoESEn_1_out.push_back(tggHiNtuplizer.phoESEn->at(i));
                tdiphoton.phoSCEta_1_out.push_back(tggHiNtuplizer.phoSCEta->at(i));
                tdiphoton.phoSCPhi_1_out.push_back(tggHiNtuplizer.phoSCPhi->at(i));
                tdiphoton.phoSCEtaWidth_1_out.push_back(tggHiNtuplizer.phoSCEtaWidth->at(i));
                tdiphoton.phoSCPhiWidth_1_out.push_back(tggHiNtuplizer.phoSCPhiWidth->at(i));
                tdiphoton.phoSCBrem_1_out.push_back(tggHiNtuplizer.phoSCBrem->at(i));
                tdiphoton.phohasPixelSeed_1_out.push_back(tggHiNtuplizer.phohasPixelSeed->at(i));
                tdiphoton.phoR9_1_out.push_back(tggHiNtuplizer.phoR9->at(i));
                tdiphoton.phoHoverE_1_out.push_back(tggHiNtuplizer.phoHoverE->at(i));
                tdiphoton.phoSigmaIEtaIEta_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta->at(i));
                tdiphoton.phoE1x3_1_out.push_back(tggHiNtuplizer.phoE1x3->at(i));
                tdiphoton.phoE2x2_1_out.push_back(tggHiNtuplizer.phoE2x2->at(i));
//                tdiphoton.phoE3x3_1_out.push_back(tggHiNtuplizer.phoE3x3->at(i));
                tdiphoton.phoE2x5Max_1_out.push_back(tggHiNtuplizer.phoE2x5Max->at(i));
//                tdiphoton.phoE1x5_1_out.push_back(tggHiNtuplizer.phoE1x5->at(i));
//                tdiphoton.phoE2x5_1_out.push_back(tggHiNtuplizer.phoE2x5->at(i));
                tdiphoton.phoE5x5_1_out.push_back(tggHiNtuplizer.phoE5x5->at(i));
//                tdiphoton.phoMaxEnergyXtal_1_out.push_back(tggHiNtuplizer.phoMaxEnergyXtal->at(i));
//                tdiphoton.phoSigmaEtaEta_1_out.push_back(tggHiNtuplizer.phoSigmaEtaEta->at(i));
//                tdiphoton.phoR1x5_1_out.push_back(tggHiNtuplizer.phoR1x5->at(i));
//                tdiphoton.phoR2x5_1_out.push_back(tggHiNtuplizer.phoR2x5->at(i));
                tdiphoton.phoESEffSigmaRR_1_out.push_back(tggHiNtuplizer.phoESEffSigmaRR->at(i));
                tdiphoton.phoSigmaIEtaIEta_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta_2012->at(i));
                tdiphoton.phoSigmaIEtaIPhi_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->at(i));
                tdiphoton.phoSigmaIPhiIPhi_2012_1_out.push_back(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->at(i));
                tdiphoton.phoE1x3_2012_1_out.push_back(tggHiNtuplizer.phoE1x3_2012->at(i));
                tdiphoton.phoE2x2_2012_1_out.push_back(tggHiNtuplizer.phoE2x2_2012->at(i));
//                tdiphoton.phoE3x3_2012_1_out.push_back(tggHiNtuplizer.phoE3x3_2012->at(i));
                tdiphoton.phoE2x5Max_2012_1_out.push_back(tggHiNtuplizer.phoE2x5Max_2012->at(i));
                tdiphoton.phoE5x5_2012_1_out.push_back(tggHiNtuplizer.phoE5x5_2012->at(i));
                tdiphoton.phoBC1E_1_out.push_back(tggHiNtuplizer.phoBC1E->at(i));
                tdiphoton.phoBC1Eta_1_out.push_back(tggHiNtuplizer.phoBC1Eta->at(i));
                tdiphoton.phoBC2E_1_out.push_back(tggHiNtuplizer.phoBC2E->at(i));
                tdiphoton.phoBC2Eta_1_out.push_back(tggHiNtuplizer.phoBC2Eta->at(i));
                tdiphoton.pho_ecalClusterIsoR2_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR2->at(i));
                tdiphoton.pho_ecalClusterIsoR3_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR3->at(i));
                tdiphoton.pho_ecalClusterIsoR4_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR4->at(i));
                tdiphoton.pho_ecalClusterIsoR5_1_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR5->at(i));
                tdiphoton.pho_hcalRechitIsoR1_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR1->at(i));
                tdiphoton.pho_hcalRechitIsoR2_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR2->at(i));
                tdiphoton.pho_hcalRechitIsoR3_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR3->at(i));
                tdiphoton.pho_hcalRechitIsoR4_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR4->at(i));
                tdiphoton.pho_hcalRechitIsoR5_1_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR5->at(i));
                tdiphoton.pho_trackIsoR1PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR1PtCut20->at(i));
                tdiphoton.pho_trackIsoR2PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR2PtCut20->at(i));
                tdiphoton.pho_trackIsoR3PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR3PtCut20->at(i));
                tdiphoton.pho_trackIsoR4PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR4PtCut20->at(i));
                tdiphoton.pho_trackIsoR5PtCut20_1_out.push_back(tggHiNtuplizer.pho_trackIsoR5PtCut20->at(i));
                tdiphoton.pho_swissCrx_1_out.push_back(tggHiNtuplizer.pho_swissCrx->at(i));
                tdiphoton.pho_seedTime_1_out.push_back(tggHiNtuplizer.pho_seedTime->at(i));

                tdiphoton.matched_eleIndex_1_out.push_back(matched_eleIndex_tmp.at(i));
                tdiphoton.matched_eleCharge_1_out.push_back(matched_eleCharge_tmp.at(i));
                tdiphoton.matched_elePt_1_out.push_back(matched_elePt_tmp.at(i));
                tdiphoton.matched_eleEta_1_out.push_back(matched_eleEta_tmp.at(i));
                tdiphoton.matched_elePhi_1_out.push_back(matched_elePhi_tmp.at(i));
                tdiphoton.matched_eleTrkPt_1_out.push_back(matched_eleTrkPt_tmp.at(i));

                tdiphoton.phoE_2_out.push_back(tggHiNtuplizer.phoE->at(j));
                tdiphoton.phoEt_2_out.push_back(tggHiNtuplizer.phoEt->at(j));
                tdiphoton.phoEta_2_out.push_back(tggHiNtuplizer.phoEta->at(j));
                tdiphoton.phoPhi_2_out.push_back(tggHiNtuplizer.phoPhi->at(j));
                tdiphoton.phoSCE_2_out.push_back(tggHiNtuplizer.phoSCE->at(j));
                tdiphoton.phoSCRawE_2_out.push_back(tggHiNtuplizer.phoSCRawE->at(j));
                tdiphoton.phoESEn_2_out.push_back(tggHiNtuplizer.phoESEn->at(j));
                tdiphoton.phoSCEta_2_out.push_back(tggHiNtuplizer.phoSCEta->at(j));
                tdiphoton.phoSCPhi_2_out.push_back(tggHiNtuplizer.phoSCPhi->at(j));
                tdiphoton.phoSCEtaWidth_2_out.push_back(tggHiNtuplizer.phoSCEtaWidth->at(j));
                tdiphoton.phoSCPhiWidth_2_out.push_back(tggHiNtuplizer.phoSCPhiWidth->at(j));
                tdiphoton.phoSCBrem_2_out.push_back(tggHiNtuplizer.phoSCBrem->at(j));
                tdiphoton.phohasPixelSeed_2_out.push_back(tggHiNtuplizer.phohasPixelSeed->at(j));
                tdiphoton.phoR9_2_out.push_back(tggHiNtuplizer.phoR9->at(j));
                tdiphoton.phoHoverE_2_out.push_back(tggHiNtuplizer.phoHoverE->at(j));
                tdiphoton.phoSigmaIEtaIEta_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta->at(j));
                tdiphoton.phoE1x3_2_out.push_back(tggHiNtuplizer.phoE1x3->at(j));
                tdiphoton.phoE2x2_2_out.push_back(tggHiNtuplizer.phoE2x2->at(j));
//                tdiphoton.phoE3x3_2_out.push_back(tggHiNtuplizer.phoE3x3->at(j));
                tdiphoton.phoE2x5Max_2_out.push_back(tggHiNtuplizer.phoE2x5Max->at(j));
//                tdiphoton.phoE1x5_2_out.push_back(tggHiNtuplizer.phoE1x5->at(j));
//                tdiphoton.phoE2x5_2_out.push_back(tggHiNtuplizer.phoE2x5->at(j));
                tdiphoton.phoE5x5_2_out.push_back(tggHiNtuplizer.phoE5x5->at(j));
//                tdiphoton.phoMaxEnergyXtal_2_out.push_back(tggHiNtuplizer.phoMaxEnergyXtal->at(j));
//                tdiphoton.phoSigmaEtaEta_2_out.push_back(tggHiNtuplizer.phoSigmaEtaEta->at(j));
//                tdiphoton.phoR1x5_2_out.push_back(tggHiNtuplizer.phoR1x5->at(j));
//                tdiphoton.phoR2x5_2_out.push_back(tggHiNtuplizer.phoR2x5->at(j));
                tdiphoton.phoESEffSigmaRR_2_out.push_back(tggHiNtuplizer.phoESEffSigmaRR->at(j));
                tdiphoton.phoSigmaIEtaIEta_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIEta_2012->at(j));
                tdiphoton.phoSigmaIEtaIPhi_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIEtaIPhi_2012->at(j));
                tdiphoton.phoSigmaIPhiIPhi_2012_2_out.push_back(tggHiNtuplizer.phoSigmaIPhiIPhi_2012->at(j));
                tdiphoton.phoE1x3_2012_2_out.push_back(tggHiNtuplizer.phoE1x3_2012->at(j));
                tdiphoton.phoE2x2_2012_2_out.push_back(tggHiNtuplizer.phoE2x2_2012->at(j));
//                tdiphoton.phoE3x3_2012_2_out.push_back(tggHiNtuplizer.phoE3x3_2012->at(j));
                tdiphoton.phoE2x5Max_2012_2_out.push_back(tggHiNtuplizer.phoE2x5Max_2012->at(j));
                tdiphoton.phoE5x5_2012_2_out.push_back(tggHiNtuplizer.phoE5x5_2012->at(j));
                tdiphoton.phoBC1E_2_out.push_back(tggHiNtuplizer.phoBC1E->at(j));
                tdiphoton.phoBC1Eta_2_out.push_back(tggHiNtuplizer.phoBC1Eta->at(j));
                tdiphoton.phoBC2E_2_out.push_back(tggHiNtuplizer.phoBC2E->at(j));
                tdiphoton.phoBC2Eta_2_out.push_back(tggHiNtuplizer.phoBC2Eta->at(j));
                tdiphoton.pho_ecalClusterIsoR2_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR2->at(j));
                tdiphoton.pho_ecalClusterIsoR3_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR3->at(j));
                tdiphoton.pho_ecalClusterIsoR4_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR4->at(j));
                tdiphoton.pho_ecalClusterIsoR5_2_out.push_back(tggHiNtuplizer.pho_ecalClusterIsoR5->at(j));
                tdiphoton.pho_hcalRechitIsoR1_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR1->at(j));
                tdiphoton.pho_hcalRechitIsoR2_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR2->at(j));
                tdiphoton.pho_hcalRechitIsoR3_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR3->at(j));
                tdiphoton.pho_hcalRechitIsoR4_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR4->at(j));
                tdiphoton.pho_hcalRechitIsoR5_2_out.push_back(tggHiNtuplizer.pho_hcalRechitIsoR5->at(j));
                tdiphoton.pho_trackIsoR1PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR1PtCut20->at(j));
                tdiphoton.pho_trackIsoR2PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR2PtCut20->at(j));
                tdiphoton.pho_trackIsoR3PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR3PtCut20->at(j));
                tdiphoton.pho_trackIsoR4PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR4PtCut20->at(j));
                tdiphoton.pho_trackIsoR5PtCut20_2_out.push_back(tggHiNtuplizer.pho_trackIsoR5PtCut20->at(j));
                tdiphoton.pho_swissCrx_2_out.push_back(tggHiNtuplizer.pho_swissCrx->at(j));
                tdiphoton.pho_seedTime_2_out.push_back(tggHiNtuplizer.pho_seedTime->at(j));

                tdiphoton.matched_eleIndex_2_out.push_back(matched_eleIndex_tmp.at(j));
                tdiphoton.matched_eleCharge_2_out.push_back(matched_eleCharge_tmp.at(j));
                tdiphoton.matched_elePt_2_out.push_back(matched_elePt_tmp.at(j));
                tdiphoton.matched_eleEta_2_out.push_back(matched_eleEta_tmp.at(j));
                tdiphoton.matched_elePhi_2_out.push_back(matched_elePhi_tmp.at(j));
                tdiphoton.matched_eleTrkPt_2_out.push_back(matched_eleTrkPt_tmp.at(j));

                // diphoton
                TLorentzVector v1, v2, vSum;
                v1.SetPtEtaPhiE( tggHiNtuplizer.phoEt->at(i), tggHiNtuplizer.phoEta->at(i),
                        tggHiNtuplizer.phoPhi->at(i), tggHiNtuplizer.phoE->at(i));
                v2.SetPtEtaPhiE( tggHiNtuplizer.phoEt->at(j), tggHiNtuplizer.phoEta->at(j),
                        tggHiNtuplizer.phoPhi->at(j), tggHiNtuplizer.phoE->at(j));
                vSum = v1+v2;

                tdiphoton.diPhoM_out.push_back(vSum.M());
                tdiphoton.diPhoEn_out.push_back(vSum.Energy());
                tdiphoton.diPhoPt_out.push_back(vSum.Pt());
                tdiphoton.diPhoEta_out.push_back(vSum.Eta());
                tdiphoton.diPhoPhi_out.push_back(vSum.Phi());
            }
        }
    }
}

Double_t getDR( Double_t eta1, Double_t phi1, Double_t eta2, Double_t phi2){
  Double_t theDphi = getDPHI( phi1, phi2);
  Double_t theDeta = eta1 - eta2;
  return TMath::Sqrt ( theDphi*theDphi + theDeta*theDeta);
}

Double_t getDPHI( Double_t phi1, Double_t phi2) {
  Double_t dphi = phi1 - phi2;

  if ( dphi > 3.141592653589 )
    dphi = dphi - 2. * 3.141592653589;
  if ( dphi <= -3.141592653589 )
    dphi = dphi + 2. * 3.141592653589;

  if ( TMath::Abs(dphi) > 3.141592653589 ) {
    std::cout << " commonUtility::getDPHI error!!! dphi is bigger than 3.141592653589 " << std::endl;
  }

  return dphi;
}

#endif /* TREEHEADERS_DIPHOTONTREE_H_ */
